import * as D from './domain.js';
import * as store from './store.js';
import {phoneNumber} from './customer-domain.js';
import {el,field,check,btn,dialog,table,download} from './ui.js';
export async function saveCustomer(input,op=D.id()){
 const phone=phoneNumber(input.phone),id='phone-'+phone;
 D.assert(input.name?.trim(),'اسم العميل مطلوب.');D.assert(input.name.length<=200,'اسم العميل طويل.');
 return store.atomic(['customers/'+id,'audit/'+op],docs=>{if(docs['audit/'+op])return {result:id};const old=docs['customers/'+id];D.assert((old?.revision||0)===(input.revision||0),'العميل موجود أو تغيرت بياناته. افتح سجله من قائمة العملاء.');const at=new Date().toISOString();return {writes:{['customers/'+id]:{id,name:input.name.trim(),phone,city:input.city||'',notes:input.notes||'',marketingConsent:!!input.marketingConsent,consentUpdatedAt:old?.marketingConsent===!!input.marketingConsent?old.consentUpdatedAt:at,revision:(old?.revision||0)+1,updatedAt:at},['audit/'+op]:{id:op,kind:'customer',by:store.uid(),at,details:id}},result:id};});
}
export function customerForm(old){const op=D.id();dialog(old?'تعديل العميل':'إضافة عميل',el('div',{class:'form-grid'},field('اسم العميل','name','text',old?.name||'',{required:'',maxlength:'200'}),field('رقم واتساب مع رمز الدولة','phone','tel',old?.phone||'',{required:'',...(old?{readonly:''}:{})}),field('المدينة','city','text',old?.city||'',{maxlength:'200'}),field('ملاحظات داخلية','notes','textarea',old?.notes||'',{maxlength:'2000'}),check('وافق العميل على استلام عروض تسويقية','consent',old?.marketingConsent||false),el('p',{class:'hint full'},'الموافقة التسويقية مستقلة عن شراء المنتج. لا تُرسل أي رسائل تلقائياً.')),async f=>{await saveCustomer({name:String(f.get('name')).trim(),phone:f.get('phone'),city:f.get('city'),notes:f.get('notes'),marketingConsent:f.has('consent'),revision:old?.revision||0},op);return 'تم حفظ بيانات العميل في السجل الخاص بالإدارة.';});}
export function customerPage(rows,orders){const q=el('input',{type:'search','aria-label':'بحث العملاء',placeholder:'ابحث بالاسم أو رقم الهاتف…'}),body=el('div');function draw(){const term=q.value.trim().toLowerCase();body.replaceChildren(table(['العميل','واتساب','المدينة','العروض','الطلبات المرتبطة','إجراء'],rows.filter(c=>[c.name,c.phone].join(' ').toLowerCase().includes(term)).map(c=>[c.name,c.phone,c.city||'—',c.marketingConsent?'موافق':'غير مشترك',String(orders.filter(o=>o.customerId===c.id).length),btn('تعديل',()=>customerForm(c))])));}q.addEventListener('input',draw);draw();return [el('h1',{},'العملاء'),el('p',{},'سجل خاص للإدارة. أضف العميل هنا ثم اختره عند تسجيل البيع. الطلبات القديمة تبقى محفوظة بأسماء أصحابها.'),el('div',{class:'actions'},btn('+ إضافة عميل',()=>customerForm(),'button primary'),btn('تصدير الموافقين على العروض',()=>download('temo-marketing-consented.json',rows.filter(c=>c.marketingConsent).map(c=>({name:c.name,phone:c.phone,city:c.city}))))),q,body];}
