import {saveCustomer,linkOrderCustomer,mergeCustomers} from './service.js';
export {saveCustomer} from './service.js';
import * as D from './domain.js';
import * as store from './store.js';
import {phoneNumber} from './customer-domain.js';
import {el,field,check,btn,dialog,table,download,select} from './ui.js';
export function customerForm(old){const op=D.id();dialog(old?'تعديل العميل':'إضافة عميل',el('div',{class:'form-grid'},field('اسم العميل','name','text',old?.name||'',{required:'',maxlength:'200'}),field('رقم واتساب مع رمز الدولة','phone','tel',old?.phone||'',{...(!old?{required:''}:{}),...(old?.phone?{readonly:''}:{})}),field('المدينة','city','text',old?.city||'',{maxlength:'200'}),field('ملاحظات داخلية','notes','textarea',old?.notes||'',{maxlength:'2000'}),check('وافق العميل على استلام عروض تسويقية','consent',old?.marketingConsent||false),el('p',{class:'hint full'},'الموافقة التسويقية مستقلة عن شراء المنتج. لا تُرسل أي رسائل تلقائياً.')),async f=>{await saveCustomer({...(old?{id:old.id}:{}),name:String(f.get('name')).trim(),phone:f.get('phone'),city:f.get('city'),notes:f.get('notes'),marketingConsent:f.has('consent'),revision:old?.revision||0},op);return 'تم حفظ بيانات العميل في السجل الخاص بالإدارة.';});}
export function customerPage(rows,orders,openOrder){const canonical=id=>{const seen=new Set();while(id&&!seen.has(id)){seen.add(id);const c=rows.find(x=>x.id===id);if(!c?.mergedInto)return id;id=c.mergedInto;}return '';};const activeRows=rows.filter(c=>!c.mergedInto);const q=el('input',{type:'search','aria-label':'بحث العملاء',placeholder:'ابحث بالاسم أو رقم الهاتف…'}),body=el('div');function profile(c){const related=orders.filter(o=>canonical(o.customerId)===c.id),active=related.filter(o=>['sold','reserved'].includes(o.status));dialog('ملف العميل — '+c.name,el('div',{class:'stack'},el('p',{},(c.phone||'بدون رقم جوال')+' · '+(c.city||'المدينة غير محددة')),el('p',{},'المستلم للطلبات النشطة: '+D.formatMoney(active.reduce((s,o)=>s+o.paid,0))+' · المتبقي: '+D.formatMoney(active.reduce((s,o)=>s+o.total-o.paid,0))),...related.map(o=>el('section',{class:'panel stack'},el('strong',{},o.number),el('p',{},D.paymentState(o).status+' · '+({pending:'قيد التجهيز',shipped:'تم الشحن',delivered:'تم التسليم',issue:'مشكلة بالشحن'}[o.fulfillment]||'قيد التجهيز')),el('p',{},'الإجمالي: '+D.formatMoney(o.total)),openOrder?btn('تفاصيل الطلب والمدفوعات',()=>openOrder(o)):null)),!related.length?el('p',{},'لا توجد طلبات مرتبطة بهذا العميل.'):null));}const unlinked=new Map();for(const o of orders){if(!o.customerId&&!o.customerPhone&&o.customer?.trim()){const k=o.customer.trim().toLowerCase();if(!unlinked.has(k))unlinked.set(k,[]);unlinked.get(k).push(o);}}
const linkPanel=el('section',{class:'panel stack'},el('h2',{},'عملاء الطلبات السابقة غير المرتبطة'),...Array.from(unlinked.values()).map(group=>btn('إضافة وربط '+group[0].customer+' ('+group.length+' طلب)',()=>{const op=D.id();dialog('إضافة عميل وربط طلباته',el('p',{},'إضافة '+group[0].customer+' إلى العملاء وربط '+group.length+' طلب. لن تتغير المبالغ أو الكميات أو حالة الطلب.'),async()=>{await linkOrderCustomer({name:group[0].customer,orders:group.map(o=>({id:o.id,revision:o.revision}))},op);return 'تمت إضافة العميل وربط طلباته السابقة بنجاح.';});})));
function draw(){const term=q.value.trim().toLowerCase();body.replaceChildren(table(['العميل','واتساب','المدينة','العروض','الطلبات المرتبطة','إجراء'],activeRows.filter(c=>[c.name,c.phone].join(' ').toLowerCase().includes(term)).map(c=>[c.name,c.phone||'—',c.city||'—',c.marketingConsent?'موافق':'غير مشترك',String(orders.filter(o=>canonical(o.customerId)===c.id).length),el('div',{class:'actions'},btn('ملف العميل',()=>profile(c)),btn('تعديل',()=>customerForm(c)))])));}q.addEventListener('input',draw);draw();return [el('h1',{},'العملاء'),el('p',{},'سجل خاص للإدارة. يُضاف العميل تلقائياً عند تسجيل بيع أو حجز، حتى دون رقم جوال. اختر العميل المسجل عند تكرار التعامل معه.'),el('div',{class:'actions'},btn('+ إضافة عميل',()=>customerForm(),'button primary'),btn('دمج ملفين',()=>{const options=[['','اختر العميل'],...activeRows.map(c=>[c.id,c.name+(c.phone?' · '+c.phone:'')])];dialog('اختيار ملفي العميل',el('div',{class:'stack'},select('الملف المراد ضمه','merge-source',options),select('الملف الذي سيبقى','merge-target',options)),f=>{const a=activeRows.find(c=>c.id===f.get('merge-source')),b=activeRows.find(c=>c.id===f.get('merge-target'));D.assert(a&&b&&a.id!==b.id,'اختر ملفين مختلفين.');setTimeout(()=>{const op=D.id();dialog('تأكيد دمج العميل',el('p',{},'ضم '+a.name+' ('+(a.phone||'بدون رقم')+') إلى '+b.name+' ('+(b.phone||'بدون رقم')+'). ستظهر طلباتهما في الملف المتبقي، مع الاحتفاظ بالملف السابق وسجل الدمج. لا تتغير حسابات الدخول أو الدفعات.'),()=>mergeCustomers({sourceId:a.id,targetId:b.id,sourceRevision:a.revision,targetRevision:b.revision},op));},0);return '';});}),btn('تصدير الموافقين على العروض',()=>download('temo-marketing-consented.json',activeRows.filter(c=>c.marketingConsent).map(c=>({name:c.name,phone:c.phone,city:c.city}))))),q,body,unlinked.size?linkPanel:null];}
