import {firebaseConfig} from './config.js';
import {el,btn,field,dialog,notice} from './ui.js';
let auth,sdk,ready,onOrders=()=>{},verificationNotice='';
async function connect(){if(!ready)ready=(async()=>{const base='https://www.gstatic.com/firebasejs/12.19.0/';const [app,a]=await Promise.all([import(base+'firebase-app.js'),import(base+'firebase-auth.js')]);sdk=a;const instance=app.getApps().find(x=>x.name==='shop-customer')||app.initializeApp(firebaseConfig,'shop-customer');auth=a.getAuth(instance);auth.languageCode='ar';await a.setPersistence(auth,a.browserLocalPersistence);await auth.authStateReady();})();return ready;}
const message=e=>({ 'auth/invalid-credential':'البريد أو كلمة المرور غير صحيحة.','auth/email-already-in-use':'هذا البريد مسجل؛ سجل الدخول أو استعد كلمة المرور.','auth/weak-password':'استخدم كلمة مرور أقوى من 8 أحرف على الأقل.','auth/invalid-email':'أدخل بريداً إلكترونياً صحيحاً.','auth/too-many-requests':'محاولات كثيرة؛ انتظر قليلاً ثم حاول مجدداً.','auth/network-request-failed':'تعذر الاتصال؛ تحقق من الإنترنت.','auth/quota-exceeded':'وصلت خدمة البريد إلى حد الإرسال؛ حاول لاحقاً.'}[e.code]||'تعذر إكمال العملية. أعد المحاولة.');
export async function customerToken(){await connect();return auth.currentUser?auth.currentUser.getIdToken():null;}
export async function requireCustomer(next){await connect();if(!auth.currentUser){accountForm(false,next);return false;}await sdk.reload(auth.currentUser);if(!auth.currentUser.emailVerified){verification(next);return false;}await auth.currentUser.getIdToken(true);return true;}
export function initCustomerAccount(orders){onOrders=orders;const button=btn('حسابي / طلباتي',()=>accountHome(),'button');document.querySelector('.topbar').append(button);}
async function accountHome(){await connect();if(!auth.currentUser)return accountForm(false,onOrders);if(!auth.currentUser.emailVerified)return verification(onOrders);dialog('حسابي',el('div',{class:'stack'},el('p',{dir:'ltr'},auth.currentUser.email),btn('طلباتي',onOrders,'button primary'),btn('تسجيل الخروج',async()=>{await sdk.signOut(auth);document.querySelector('#dialog').close();notice('تم تسجيل الخروج من حساب المتجر.');})));}
function accountForm(register,next){const box=el('div',{class:'stack'},el('p',{},'احفظ طلباتك وتابع الدفع والشحن من أي جهاز باستخدام حسابك.'),field('البريد الإلكتروني','email','email','',{required:'',autocomplete:'email',dir:'ltr'}),field('كلمة المرور','password','password','',{required:'',minlength:register?'8':'1',autocomplete:register?'new-password':'current-password'}),register?field('تأكيد كلمة المرور','confirm','password','',{required:'',minlength:'8',autocomplete:'new-password'}):null,btn(register?'لدي حساب — تسجيل الدخول':'حساب جديد',()=>accountForm(!register,next)),btn('نسيت كلمة المرور',resetForm));dialog(register?'إنشاء حساب عميل':'تسجيل دخول العميل',box,async f=>{await connect();if(register&&f.get('password')!==f.get('confirm'))throw Error('كلمتا المرور غير متطابقتين.');try{if(register)await sdk.createUserWithEmailAndPassword(auth,String(f.get('email')).trim(),f.get('password'));else await sdk.signInWithEmailAndPassword(auth,String(f.get('email')).trim(),f.get('password'));}catch(e){throw Error(message(e));}if(!auth.currentUser.emailVerified){if(register){try{await sdk.sendEmailVerification(auth.currentUser);verificationNotice='قبلت خدمة البريد طلب الإرسال. قد يتأخر وصول الرسالة؛ راجع الرسائل غير المرغوب فيها.';}catch(e){verificationNotice='لم يتم إرسال رسالة التحقق: '+message(e);}}setTimeout(()=>verification(next),0);}else setTimeout(next,0);});document.querySelector('#dialog button[type=submit]').textContent=register?'إنشاء الحساب':'تسجيل الدخول';}
function verification(next){
 const status=el('p',{role:'status'},verificationNotice||'إذا لم تجد الرسالة، تحقق من البريد أدناه ثم اطلب إعادة الإرسال مرة واحدة.');
 const resend=btn('إعادة إرسال رسالة التحقق',async()=>{resend.disabled=true;status.textContent='جارٍ طلب إرسال رسالة التحقق…';try{await sdk.sendEmailVerification(auth.currentUser);verificationNotice='قبلت خدمة البريد طلب الإرسال. راجع البريد الوارد والرسائل غير المرغوب فيها وابحث عن Temo أو Firebase.';status.textContent=verificationNotice;}catch(e){status.textContent=verificationNotice='تعذر إرسال الرسالة: '+message(e);}finally{resend.textContent='يمكن إعادة المحاولة بعد دقيقة';setTimeout(()=>{resend.disabled=false;resend.textContent='إعادة إرسال رسالة التحقق';},60000);}});
 dialog('تأكيد البريد الإلكتروني',el('div',{class:'stack'},el('p',{},'لتفعيل حسابك، افتح رابط التحقق الذي يصلك على بريدك ثم اضغط متابعة.'),el('strong',{dir:'ltr'},auth.currentUser.email),status,btn('تحققت من بريدي — متابعة',async()=>{await sdk.reload(auth.currentUser);if(!auth.currentUser.emailVerified){status.textContent='البريد لم يُؤكد بعد. افتح رابط التحقق في الرسالة أولاً.';return;}await auth.currentUser.getIdToken(true);await next();},'button primary'),resend,btn('تصحيح البريد / تغيير الحساب',async()=>{await sdk.signOut(auth);verificationNotice='';accountForm(false,next);})));}
function resetForm(){dialog('استعادة كلمة المرور',field('البريد الإلكتروني','email','email','',{required:'',autocomplete:'email',dir:'ltr'}),async f=>{await connect();try{await sdk.sendPasswordResetEmail(auth,String(f.get('email')).trim());}catch(e){if(!['auth/user-not-found'].includes(e.code))throw Error(message(e));}return 'إذا كان البريد مسجلاً فستصلك رسالة استعادة كلمة المرور. راجع بريدك ومجلد الرسائل غير المرغوب فيها.';});}
