import {firebaseConfig} from './config.js';
import {el,btn,field,dialog,notice} from './ui.js';
let auth,sdk,ready,onOrders=()=>{};
async function connect(){if(!ready)ready=(async()=>{const base='https://www.gstatic.com/firebasejs/12.19.0/';const [app,a]=await Promise.all([import(base+'firebase-app.js'),import(base+'firebase-auth.js')]);sdk=a;const instance=app.getApps().find(x=>x.name==='shop-customer')||app.initializeApp(firebaseConfig,'shop-customer');auth=a.getAuth(instance);auth.languageCode='ar';await a.setPersistence(auth,a.browserLocalPersistence);await auth.authStateReady();})();return ready;}
const message=e=>({ 'auth/invalid-credential':'البريد أو كلمة المرور غير صحيحة.','auth/email-already-in-use':'هذا البريد مسجل؛ سجل الدخول أو استعد كلمة المرور.','auth/weak-password':'استخدم كلمة مرور أقوى من 8 أحرف على الأقل.','auth/invalid-email':'أدخل بريداً إلكترونياً صحيحاً.','auth/too-many-requests':'محاولات كثيرة؛ انتظر قليلاً ثم حاول مجدداً.','auth/network-request-failed':'تعذر الاتصال؛ تحقق من الإنترنت.'}[e.code]||'تعذر إكمال العملية. أعد المحاولة.');
export async function customerToken(){await connect();return auth.currentUser?auth.currentUser.getIdToken():null;}
export async function requireCustomer(next){await connect();if(!auth.currentUser){accountForm(false,next);return false;}await sdk.reload(auth.currentUser);if(!auth.currentUser.emailVerified){verification(next);return false;}await auth.currentUser.getIdToken(true);return true;}
export function initCustomerAccount(orders){onOrders=orders;const button=btn('حسابي / طلباتي',()=>accountHome(),'button');document.querySelector('.topbar').append(button);}
async function accountHome(){await connect();if(!auth.currentUser)return accountForm(false,onOrders);if(!auth.currentUser.emailVerified)return verification(onOrders);dialog('حسابي',el('div',{class:'stack'},el('p',{dir:'ltr'},auth.currentUser.email),btn('طلباتي',onOrders,'button primary'),btn('تسجيل الخروج',async()=>{await sdk.signOut(auth);document.querySelector('#dialog').close();notice('تم تسجيل الخروج من حساب المتجر.');})));}
function accountForm(register,next){const box=el('div',{class:'stack'},el('p',{},'احفظ طلباتك وتابع الدفع والشحن من أي جهاز باستخدام حسابك.'),field('البريد الإلكتروني','email','email','',{required:'',autocomplete:'email',dir:'ltr'}),field('كلمة المرور','password','password','',{required:'',minlength:register?'8':'1',autocomplete:register?'new-password':'current-password'}),register?field('تأكيد كلمة المرور','confirm','password','',{required:'',minlength:'8',autocomplete:'new-password'}):null,btn(register?'لدي حساب — تسجيل الدخول':'حساب جديد',()=>accountForm(!register,next)),btn('نسيت كلمة المرور',resetForm));dialog(register?'إنشاء حساب عميل':'تسجيل دخول العميل',box,async f=>{await connect();if(register&&f.get('password')!==f.get('confirm'))throw Error('كلمتا المرور غير متطابقتين.');try{if(register)await sdk.createUserWithEmailAndPassword(auth,String(f.get('email')).trim(),f.get('password'));else await sdk.signInWithEmailAndPassword(auth,String(f.get('email')).trim(),f.get('password'));}catch(e){throw Error(message(e));}if(!auth.currentUser.emailVerified){if(register){try{await sdk.sendEmailVerification(auth.currentUser);}catch{}}setTimeout(()=>verification(next),0);}else setTimeout(next,0);});document.querySelector('#dialog button[type=submit]').textContent=register?'إنشاء الحساب':'تسجيل الدخول';}
function verification(next){dialog('تأكيد البريد الإلكتروني',el('div',{class:'stack'},el('p',{},'افتح رسالة التحقق المرسلة إلى '+auth.currentUser.email+' ثم عد إلى هذه الصفحة. راجع مجلد الرسائل غير المرغوب فيها.'),btn('تحققت من بريدي — متابعة',async()=>{if(await requireCustomer(next))await next();},'button primary'),btn('إعادة إرسال رسالة التحقق',async()=>{try{await sdk.sendEmailVerification(auth.currentUser);notice('أُرسلت رسالة التحقق.');}catch(e){throw Error(message(e));}}),btn('تغيير الحساب / خروج',async()=>{await sdk.signOut(auth);accountForm(false,next);})));}
function resetForm(){dialog('استعادة كلمة المرور',field('البريد الإلكتروني','email','email','',{required:'',autocomplete:'email',dir:'ltr'}),async f=>{await connect();try{await sdk.sendPasswordResetEmail(auth,String(f.get('email')).trim());}catch(e){if(!['auth/user-not-found'].includes(e.code))throw Error(message(e));}return 'إذا كان البريد مسجلاً فستصلك رسالة استعادة كلمة المرور. راجع بريدك ومجلد الرسائل غير المرغوب فيها.';});}
