import test from 'node:test';import assert from 'node:assert/strict';import {createHash} from 'node:crypto';import {createHandler} from './netlify/functions/shop-orders.mjs';
const id='11111111-1111-4111-8111-111111111111',token='22222222-2222-4222-8222-222222222222';
function setup(owner='alice'){
 const docs=new Map([['shopRequests/'+id,{id,customerUid:owner,number:'WEB-T',status:'pending',items:[],createdAt:'2026-10-03',tokenHash:createHash('sha256').update(token).digest('hex')}]]);
 const snap=p=>({data:()=>structuredClone(docs.get(p)),exists:docs.has(p)});
 const db={doc:p=>({path:p,get:async()=>snap(p)}),collection:()=>({where:(k,op,v)=>({limit:()=>({get:async()=>({docs:[...docs.values()].filter(r=>r[k]===v).map(r=>({data:()=>structuredClone(r)}))})})})}),runTransaction:async fn=>{const writes=[];const result=await fn({get:async r=>snap(r.path),set:(r,d)=>writes.push([r.path,structuredClone(d)])});writes.forEach(([k,v])=>docs.set(k,v));return result;}};
 const auth={verifyIdToken:async t=>{if(!t)throw Error();return {uid:t,email:t+'@example.test',email_verified:t!=='unverified'};}};
 const handler=createHandler(async()=>({db,auth}));return {docs,call:async(body,user)=>{const r=await handler({httpMethod:'POST',headers:{origin:'https://temoplants.netlify.app','x-nf-client-connection-ip':'192.0.2.2',authorization:user?'Bearer '+user:''},body:JSON.stringify(body)});return {code:r.statusCode,...JSON.parse(r.body)};}};
}
test('customer orders are isolated by verified UID',async()=>{const {call}=setup();assert.equal((await call({action:'my-orders'},'alice')).requests.length,1);assert.equal((await call({action:'my-orders'},'bob')).requests.length,0);assert.equal((await call({action:'my-orders'},'unverified')).code,401);});
test('new account-owned order rejects another customer and guest even with tracking token',async()=>{const {call}=setup();assert.equal((await call({action:'status',id},'alice')).code,200);for(const user of [undefined,'bob','unverified'])assert.ok([401,403].includes((await call({action:'status',id,token},user)).code));});
test('legacy claim requires secret link and cannot reassign an owner',async()=>{const {call,docs}=setup(undefined);delete docs.get('shopRequests/'+id).customerUid;assert.equal((await call({action:'claim',id,token:id},'alice')).code,400);assert.equal((await call({action:'claim',id,token},'alice')).code,200);assert.equal((await call({action:'claim',id,token},'bob')).code,400);assert.equal(docs.get('shopRequests/'+id).customerUid,'alice');});
test('guests and unverified customers cannot create orders or access admin functions',async()=>{const {call}=setup();for(const user of [undefined,'unverified'])assert.equal((await call({action:'create'},user)).code,401);assert.equal((await call({action:'list'},'alice')).code,403);});
