import {el,btn,field,select,check,dialog,notice,table} from './ui.js';
import * as D from './domain.js';
import * as store from './store.js';
import * as api from './service.js';
import {estimate,market,forms,stages,safeURL,priceOverview} from './market-domain.js';
const country=[['SA','السعودية'],['KW','الكويت'],['TH','تايلند'],['CN','الصين'],['VN','فيتنام'],['US','الولايات المتحدة'],['NL','هولندا'],['DE','ألمانيا'],['FR','فرنسا'],['GB','بريطانيا'],['OTHER','بلد آخر (أدخل رمز ISO)']];
const currencies=['SAR','KWD','THB','CNY','VND','EUR','USD','GBP'].map(c=>[c,c]);
export function marketDialog(p,selected){
 const current=selected||p.variants.find(v=>!D.variantHidden(v))||p.variants[0];
 const type=current?.type||'',initial=/كورم|corm/i.test(type)?'corm':/كتنج|cutting/i.test(type)?'cutting':/أم|مذر|mother/i.test(type)?'mother':/شتل|baby|seedling/i.test(type)?'baby':'custom';
 const name=field('اسم النبتة','quick-name','text',p.name,{maxlength:200}),form=select('أبحث عن سعر','quick-form',forms,initial),custom=field('الصنف المخصص','quick-custom','text',initial==='custom'?type:'');
 const notes=field('حجم أو حالة مميزة (اختياري)','quick-notes','text','',{maxlength:300});
 const inputs=el('div',{class:'form-grid'},name,form,custom),status=el('p',{role:'status'}),out=el('div',{class:'stack','aria-live':'polite'}),links=el('div',{class:'actions'});
 let busy=false,serial=0,last=null;
 const read=()=>({mode:'quick',name:name.querySelector('input').value.trim(),form:form.querySelector('select').value,custom:custom.querySelector('input').value.trim(),condition:notes.querySelector('input').value.trim(),stage:'unknown'});
 const fmt=(n,c)=>new Intl.NumberFormat('ar-SA',{maximumFractionDigits:2}).format(n)+' '+c;
 function update(){serial++;last=null;out.replaceChildren();const i=read();custom.hidden=i.form!=='custom';const term=i.name+' '+(i.form==='custom'?i.custom:i.form==='mother'?'plant':i.form==='baby'?'baby plant':i.form)+' price';links.replaceChildren(...[['فتح بحث Google',term],['إعلانات Instagram العامة',term+' site:instagram.com']].map(([label,q])=>el('a',{class:'button subtle',href:'https://www.google.com/search?q='+encodeURIComponent(q),target:'_blank',rel:'noopener noreferrer'},label)));}
 inputs.addEventListener('input',update);notes.addEventListener('input',update);update();
 function card(r){return el('article',{class:'panel stack'},el('a',{href:safeURL(r.url),target:'_blank',rel:'noopener noreferrer'},r.seller||new URL(r.url).hostname),el('strong',{},fmt(r.price/r.units,r.currency)+' / قطعة'),el('p',{},r.description||r.name),el('p',{class:'hint'},(forms.find(([k])=>k===r.form)?.[1]||r.custom||'شكل غير محدد')+' · '+(r.country||'البلد غير محدد')+' · '+(r.saleType==='wholesale'?'جملة':r.saleType==='auction'?'مزاد':'سعر إعلان')),el('p',{class:'hint'},r.date?'تاريخ الإعلان: '+r.date:'تاريخ الإعلان غير مذكور'))}
 async function search(refresh=false){
  if(busy)return;const i=read();if(!i.name){status.textContent='اكتب اسم النبتة أولاً.';return;}if(i.form!=='custom')i.custom='';
  if(store.demo){status.textContent='البحث الحي متاح بعد تسجيل الدخول. يمكنك تجربة روابط Google أدناه.';return;}
  const ticket=serial;busy=true;go.disabled=true;go.textContent='جارٍ البحث…';status.textContent='نبحث عن أسعار منشورة وروابطها. قد يستغرق البحث نحو دقيقة.';out.replaceChildren();
  try{const token=await store.marketToken(),response=await fetch('/.netlify/functions/market-estimate',{method:'POST',headers:{'Content-Type':'application/json',Authorization:'Bearer '+token},body:JSON.stringify({input:i,refresh}),signal:AbortSignal.timeout(60000)});
   if(!response.headers.get('content-type')?.includes('application/json'))throw Error('خدمة البحث غير متاحة حالياً. استخدم رابط Google أدناه.');
   const data=await response.json();if(!response.ok)throw Error(data.error||'تعذر البحث.');if(ticket!==serial)return;
   const overview=priceOverview(i,data.comparisons||[]);last={input:i,...data,overview};status.textContent='آخر بحث: '+new Date(data.searchedAt).toLocaleString('ar-SA')+(data.cached?' · نتيجة محفوظة':'');
   out.append(el('h3',{},data.summary||overview.groups.length?'نتيجة بحث السعر':'لم نجد سعراً موثقاً لهذا الصنف في هذا البحث'));
   if(data.summary){out.append(el('div',{class:'panel',style:'white-space:pre-wrap;overflow-wrap:anywhere;line-height:1.9'},data.summary));for(const source of data.sources||[])if(safeURL(source.url))out.append(el('a',{href:safeURL(source.url),target:'_blank',rel:'noopener noreferrer'},source.title||'المصدر'));}
   for(const g of overview.groups){out.append(el('section',{class:'panel stack'},el('h4',{},g.region==='local'?'السعودية':'متاجر خارج السعودية'),el('strong',{},g.rows.length===1?fmt(g.min,g.currency):fmt(g.min,g.currency)+' – '+fmt(g.max,g.currency)),el('p',{class:'hint'},g.rows.length+' إعلان · '+(g.rows.length===1?'سعر إعلان واحد، وليس نطاق السوق':'أقل وأعلى سعر للقطعة في النتائج المطابقة')), ...g.rows.map(card)));}
   out.append(el('p',{class:'hint'},'مؤشر أولي منخفض الثقة من أسعار الإعلانات، وليس مبيعات مؤكدة أو تقييماً لنبتتك. العملات معروضة كما هي؛ الشحن والرسوم غير مشمولة، وقد تختلف الأحجام والحالة والتوفر.'));
   if(overview.other.length)out.append(el('details',{},el('summary',{},'نتائج لأشكال أخرى أو غير مطابقة — لا تدخل في النطاق'),...overview.other.map(card)));
   if(data.message)out.append(el('p',{class:'hint'},data.message));
   out.append(btn('تحديث البحث',()=>search(true)),btn('حفظ نتيجة البحث',async e=>{if(!last||ticket!==serial)return;const button=e.currentTarget;const id=D.id();await store.atomic(['audit/'+id],()=>({writes:{['audit/'+id]:{id,kind:'market-price-search',productId:p.id,uid:store.uid(),createdAt:new Date().toISOString(),report:last}}}));button.disabled=true;notice('حُفظت نتيجة البحث دون تغيير سعر البيع.');}));
  }catch(e){if(ticket===serial)status.textContent=e.name==='TimeoutError'?'تأخر البحث. حاول مجدداً أو افتح Google أدناه.':e.message;}finally{busy=false;go.disabled=false;go.textContent='ابحث عن السعر';}
 }
 const go=btn('ابحث عن السعر',()=>search(),'button primary');
 const history=el('div',{class:'stack'});
 dialog('بحث عن سعر تقريبي',el('div',{class:'stack market-dialog'},el('p',{class:'hint'},'الاسم والصنف فقط. نعرض الأسعار ومصادرها دون تغيير سعر البيع.'),inputs,el('details',{},el('summary',{},'تفاصيل اختيارية لتحسين البحث'),notes),go,status,out,links,el('details',{},el('summary',{},'بحث محفوظ وخيارات إضافية'),history,btn('إضافة إعلان يدوي / تحليل مفصل',()=>detailedMarketDialog(p,current)))));
 // Prevent Enter from reloading the page or silently submitting the dialog form.
 document.querySelector('#dialog form').addEventListener('submit',e=>{e.preventDefault();search();});
 store.list('audit').then(rows=>{for(const r of rows.filter(r=>r.kind==='market-price-search'&&r.productId===p.id).sort((a,b)=>b.createdAt.localeCompare(a.createdAt)).slice(0,5))history.append(el('details',{},el('summary',{},'بحث محفوظ · '+r.createdAt.slice(0,16)),el('p',{style:'white-space:pre-wrap'},r.report.summary||''),...(r.report.sources||[]).filter(s=>safeURL(s.url)).map(s=>el('a',{href:s.url,target:'_blank',rel:'noopener noreferrer'},s.title||'المصدر')),...r.report.overview.groups.flatMap(g=>g.rows.map(card)),...r.report.overview.other.map(card)));}).catch(()=>{});
}
function detailedMarketDialog(p,selected){
 let comparisons=[],result=null,serial=0,busy=false,reportSaved=false;
 const err=el('p',{role:'alert',class:'form-error'}),out=el('div',{class:'market-result','aria-live':'polite'}),cards=el('div',{class:'stack'}),history=el('div',{class:'stack'});
 const variant=select('الصنف المسجل','variant',p.variants.filter(v=>!D.variantHidden(v)).map(v=>[v.id,v.type]),selected?.id||p.variants[0]?.id);
 const details=el('div',{class:'form-grid'},variant,field('الاسم العلمي / الهجين','name','text',p.name,{maxlength:200}),select('شكل القطعة','form',forms,'baby'),field('اسم الصنف المخصص (عند اختياره)','custom'),field('الحجم / عدد الأوراق','size','text',p.size||'',{maxlength:200}),select('مرحلة النمو','stage',stages),field('الجذور والتأقلم والصحة','condition','text','',{maxlength:300}),field('التبرقش ومدى ثباته الموثق','variegation','text','',{maxlength:300}),field('الكورمة: الحجم / الكتنج: عقدة وجذور وورقة','structure','text','',{maxlength:300}),check('أؤكد الاسم والصنف؛ الصورة وحدها لا تثبت الهوية','identityConfirmed'),field('صورة حديثة اختيارية — للمرجع المحلي','photo','file','',{accept:'image/png,image/jpeg,image/webp'}));
 const value=(box,n)=>box.querySelector('[name="'+n+'"]').value.trim();
 const input=()=>({productId:p.id,variantId:value(details,'variant'),name:value(details,'name'),form:value(details,'form'),custom:value(details,'form')==='custom'?value(details,'custom'):'',size:value(details,'size'),stage:value(details,'stage'),condition:value(details,'condition'),variegation:value(details,'variegation'),structure:value(details,'structure'),identityConfirmed:details.querySelector('[name=identityConfirmed]').checked});
 function infer(){const v=p.variants.find(v=>v.id===value(details,'variant'));const t=v?.type||'';details.querySelector('[name=form]').value=/كورم|corm/i.test(t)?'corm':/كتنج|cutting/i.test(t)?'cutting':/أم|مذر|mother/i.test(t)?'mother':/شتل|baby|seedling/i.test(t)?'baby':'custom';details.querySelector('[name=custom]').value=details.querySelector('[name=form]').value==='custom'?t:'';}
 infer();variant.addEventListener('change',infer);
 function invalidate(){serial++;result=null;reportSaved=false;out.replaceChildren(el('p',{class:'hint'},'اضغط «احسب التقدير» بعد مراجعة المدخلات والمقارنات.'));}
 details.addEventListener('input',invalidate);
 const preview=el('img',{class:'market-photo',hidden:''});details.append(preview);let photoURL;
 details.querySelector('[name=photo]').addEventListener('change',e=>{if(photoURL)URL.revokeObjectURL(photoURL);const f=e.target.files[0];preview.hidden=true;if(!f)return;if(f.size>5*1024*1024){err.textContent='الحد للصورة 5MB.';e.target.value='';return;}photoURL=URL.createObjectURL(f);preview.src=photoURL;preview.hidden=false;});
 document.getElementById('dialog').addEventListener('close',()=>{if(photoURL)URL.revokeObjectURL(photoURL);},{once:true});
 function addComparison(seed={}){
  if(comparisons.length>=20)throw new Error('الحد 20 مقارنة في التقدير.');
  const i=input(),r={...seed},box=el('details',{class:'market-comparison',open:''});
  const body=el('div',{class:'form-grid'},field('المصدر / البائع','seller','text',r.seller||'',{maxlength:150}),field('رابط الإعلان HTTPS','url','url',r.url||'',{maxlength:1500}),field('تاريخ السعر / الإعلان','date','date',r.date||''),field('الاسم العلمي في الإعلان','name','text',r.name||i.name),select('شكل القطعة','form',forms,r.form||i.form),field('الصنف المخصص','custom','text',r.custom||i.custom),select('مرحلة النمو','stage',stages,r.stage||i.stage),field('وصف القطعة وحجمها وحالتها','description','textarea',r.description||'',{maxlength:1000}),select('بلد البائع','country',country,r.country||market.country),field('رمز البلد الآخر (حرفان)','otherCountry','text','',{maxlength:2}),field('سعر الإعلان','price','number',r.price??'',{min:0,step:'any'}),field('عدد القطع المشمولة بالسعر','units','number',r.units??1,{min:1,step:1}),select('العملة','currency',currencies,r.currency||market.currency),select('نوع الإعلان','saleType',[['retail','تجزئة'],['wholesale','جملة'],['auction','مزاد']],r.saleType||'retail'),select('حالة السعر','status',[['asking','سعر عرض'],['sold','بيع مكتمل']],r.status||'asking'),check('يوجد دليل صريح على إتمام البيع بالسعر المذكور','soldEvidence',false),select('تطابق الحجم والحالة والتبرقش','match',[['unknown','لم أتحقق'],['exact','متطابق / قابل للمقارنة'],['different','مختلف']],r.match||'unknown'),check('راجعت المصدر والسعر والعملة والتاريخ وتطابق القطعة','reviewed',false),field('صورة إعلان بدلاً من الرابط (تُحفظ خاصة مع التقدير)','evidence','file','',{accept:'image/jpeg,image/png,image/webp'}));
  const extra=el('details',{class:'full'},el('summary',{},'سعر الصرف وتكلفة الوصول — بالريال السعودي للقطعة'),el('div',{class:'form-grid'},field('ريال لكل وحدة من العملة الأجنبية','fx','number',r.fx??'',{min:0,step:'any'}),field('تاريخ سعر الصرف','fxDate','date',r.fxDate||''),field('مصدر سعر الصرف HTTPS','fxSource','url',r.fxSource||''),...['shipping','duties','permits','acclimation'].map((k,j)=>field(['شحن القطعة','رسوم وجمارك القطعة','تصاريح القطعة','تأقلم القطعة'][j]+' — فارغ = غير معروف',k,'number','',{min:0,step:'.01'}))));body.append(extra);
  box.append(el('summary',{},r.origin==='ai'?'مقارنة من البحث — تحتاج مراجعتك':'مقارنة مقدمة منك'),body,btn('إزالة المقارنة',()=>{box.remove();comparisons=comparisons.filter(x=>x.box!==box);invalidate();},'button subtle'));
  const entry={box,read(){const o={origin:r.origin||'manual',observedAt:r.observedAt||new Date().toISOString(),quote:r.quote||'',evidenceData:entry.evidenceData||'',evidenceId:entry.evidenceData?entry.evidenceId:''};for(const n of ['seller','url','date','name','form','custom','stage','description','country','currency','saleType','status','match','fxDate','fxSource'])o[n]=value(body,n);if(o.form!=='custom')o.custom='';if(o.country==='OTHER')o.country=value(body,'otherCountry').toUpperCase();for(const n of ['price','units','fx','shipping','duties','permits','acclimation'])o[n]=value(body,n)===''?null:Number(value(body,n));for(const n of ['reviewed','soldEvidence'])o[n]=body.querySelector('[name='+n+']').checked;return o;}};
  body.querySelector('[name=evidence]').addEventListener('change',async e=>{try{entry.evidenceData='';const f=e.target.files[0];if(!f)return;if(!['image/jpeg','image/png','image/webp'].includes(f.type)||f.size>100000)throw new Error('صورة الإعلان يجب أن تكون JPG/PNG/WebP وأصغر من 100KB؛ استخدم الرابط للصورة الأكبر.');entry.evidenceData=await new Promise((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(reader.result);reader.onerror=reject;reader.readAsDataURL(f);});entry.evidenceId=D.id();invalidate();}catch(e){err.textContent=e.message;}});
  const suffix=D.id();body.querySelectorAll('[id]').forEach(n=>{const old=n.id;n.id=old+'-'+suffix;body.querySelectorAll('label').forEach(l=>{if(l.htmlFor===old)l.htmlFor=n.id;});});body.addEventListener('input',invalidate);comparisons.push(entry);cards.append(box);invalidate();
 }
 function calculate(){err.textContent='';const i=input();if(!i.name||!i.identityConfirmed)throw new Error('أكّد هوية النبات واكتب الاسم أولاً.');result=estimate(i,comparisons.map(x=>x.read()));reportSaved=false;showResult();}
 function showResult(){
  const r=result;
  const sections=['local','foreign','excluded'].map((k,j)=>el('section',{},
   el('h4',{},['المقارنات المحلية','الأسواق الخارجية — لا تحدد السعر المحلي وحدها','مقارنات مستبعدة'][j]),
   table(['المصدر','القطعة / التاريخ','السعر','الملاحظة'],r[k].map(x=>[
    safeURL(x.url)?el('a',{href:safeURL(x.url),target:'_blank',rel:'noopener noreferrer'},x.seller||'فتح المصدر'):el('span',{},'صورة مقدمة منك'),
    (x.description||x.name)+' · '+x.country+' · '+x.date,
    x.price+' '+x.currency+' / '+x.units+' قطعة',
    x.why||(x.country!==market.country?'تكلفة الوصول: '+(x.landed===null?'غير مكتملة':D.formatMoney(Math.round(x.landed*market.scale))):'مطابقة ومراجعة')
   ]))));
  out.replaceChildren(...[
   el('h3',{},r.range?'النطاق المتوقع: '+r.range.map(D.formatMoney).join(' – '):'البيانات غير كافية لتقدير موثوق'),
   el('p',{},'الثقة: '+r.confidence+' · '+r.local.length+' مقارنة محلية · '+r.foreign.length+' خارجية'),
   el('p',{class:'hint'},'تاريخ الحساب: '+r.createdAt),...r.reasons.map(x=>el('p',{class:'hint'},x)),
   r.median!==null?el('p',{},'السعر المعتاد المقترح: '+D.formatMoney(r.median)):null,
   el('p',{},r.quick?'نطاق منخفض مستند إلى مبيعات مكتملة (لا يضمن سرعة البيع): '+r.quick.map(D.formatMoney).join(' – '):'لا تتوفر أدلة كافية لنطاق بيع سريع.'),
   ...sections,btn('حفظ التقدير',save,'button primary'),r.median!==null?btn('استخدام السعر المقترح',apply):null].filter(Boolean));
 }
 async function save(){if(!result||reportSaved)return;if(JSON.stringify(result).length>650000)throw new Error('صور المقارنات كبيرة؛ قلل عددها قبل الحفظ.');const id=D.id(),record={id,kind:'market-estimate',productId:p.id,createdAt:new Date().toISOString(),uid:store.uid(),report:result};await store.atomic(['audit/'+id],()=>({writes:{['audit/'+id]:record}}));reportSaved=true;notice('حُفظ التقدير في سجل الإدارة الخاص.');await loadHistory();}
 function apply(){
  if(!result?.median)return;const r=result;
  const consent=check('أوافق على تغيير سعر هذا الصنف فقط إلى '+D.formatMoney(r.median),'confirm-market-price');
  const box=el('div',{class:'panel stack'},el('h4',{},'تأكيد تحديث سعر البيع'),consent);
  const submit=btn('تأكيد تغيير السعر',async()=>{if(!consent.querySelector('input').checked)throw new Error('حدد الموافقة أولاً.');submit.disabled=true;try{const fresh=await store.get('products/'+p.id);D.assert(fresh&&fresh.revision===p.revision,'تغيرت النبتة. أغلق النافذة وأعد فتحها.');await api.saveProduct({...fresh,variants:fresh.variants.map(v=>v.id===r.input.variantId?{...v,price:r.median}:v)});notice('تم تحديث سعر الصنف بعد تأكيدك.');document.getElementById('dialog').close();}finally{submit.disabled=false;}},'button primary');
  box.append(submit,btn('إلغاء تغيير السعر',()=>box.remove()));out.append(box);consent.querySelector('input').focus();
 }
 async function search(refresh=false){if(busy)return;const i=input();if(!i.identityConfirmed||!i.name)throw new Error('أكّد هوية النبات أولاً.');if(store.demo)throw new Error('البحث الحي غير متصل في المعاينة. أضف مقارناتك يدوياً لتجربة الحساب.');busy=true;const ticket=serial;searchButton.disabled=true;err.textContent='جارٍ البحث في المصادر المتاحة…';try{const token=await store.marketToken();const response=await fetch('/.netlify/functions/market-estimate',{method:'POST',headers:{'Content-Type':'application/json',Authorization:'Bearer '+token},body:JSON.stringify({input:i,refresh}),signal:AbortSignal.timeout(60000)});if(!response.headers.get('content-type')?.includes('application/json'))throw new Error('خدمة البحث لم تُنشر بعد. يمكنك استخدام المقارنات اليدوية الآن.');const data=await response.json();if(!response.ok)throw new Error(data.error||'تعذر البحث.');if(ticket!==serial)throw new Error('تغيرت المدخلات أثناء البحث؛ أعد البحث للصنف الجديد.');for(const r of data.comparisons||[])addComparison(r);err.textContent='آخر بحث: '+data.searchedAt+(data.cached?' (محفوظ مؤقتاً)':'')+' — '+(data.message||'راجع المصادر قبل حساب التقدير.');}catch(e){err.textContent=e.name==='TimeoutError'?'انتهت مهلة البحث؛ مدخلاتك محفوظة. حاول لاحقاً.':e.message;}finally{busy=false;searchButton.disabled=false;}}
 async function loadHistory(){const rows=(await store.list('audit')).filter(x=>x.kind==='market-estimate'&&x.productId===p.id).sort((a,b)=>b.createdAt.localeCompare(a.createdAt)).slice(0,5);history.replaceChildren(...rows.map(x=>btn('تقدير محفوظ · '+x.createdAt.slice(0,16),()=>{dialog('تقدير سابق — للقراءة',el('div',{class:'stack'},el('p',{},x.report.input.name+' · '+x.report.input.form),el('p',{},x.report.range?x.report.range.map(D.formatMoney).join(' – '):'بيانات غير كافية'),el('p',{},x.report.reasons.join(' ')),table(['المصدر','التاريخ','السعر'],[...x.report.local,...x.report.foreign].map(r=>[safeURL(r.url)?el('a',{href:safeURL(r.url),target:'_blank',rel:'noopener'},r.seller||'المصدر'):'صورة محفوظة',r.date,r.price+' '+r.currency]))));})));}
 const searchButton=btn('بحث حي بالذكاء الاصطناعي',()=>search(),'button');
 const content=el('div',{class:'stack market-dialog'},el('p',{class:'hint'},'تقدير خاص بالإدارة · السعودية / SAR. لا يتغير سعر البيع إلا بعد تأكيدك. الصور المحلية لا تُرسل إلى مزود البحث؛ يُرسل وصف النبتة فقط.'),details,el('div',{class:'actions'},searchButton,btn('تحديث البحث',()=>search(true)),btn('+ إضافة إعلان / مقارنة يدوية',()=>addComparison())),err,cards,btn('احسب التقدير',calculate,'button primary'),out,el('details',{},el('summary',{},'آخر التقديرات المحفوظة'),history));
 dialog('تقدير سعر السوق ✨ — '+p.name,content);loadHistory().catch(e=>{err.textContent=e.message;});
}
