import {el,btn,select,field,notice} from './ui.js';
import {saleEntries} from './sale-catalog.js';
import {formatMoney} from './domain.js';
import {variantLabel} from './storefront-content.js';
let view, currentState, syncChoices;
export function marketingPage(state){
 currentState=state;if(view){syncChoices();return [view];}
 const choices=select('النبتة والصنف المتاح للبيع','marketing-product',[['','— اختر عرضاً منشوراً —'],...saleEntries(state.products).filter(x=>x.status==='live').map(({p,v})=>[p.id+'|'+v.id,p.name+' — '+variantLabel(v.type)])]);
 syncChoices=()=>{const s=choices.querySelector('select'),value=s.value,rows=saleEntries(currentState.products).filter(x=>x.status==='live');s.replaceChildren(el('option',{value:''},'— اختر عرضاً منشوراً —'),...rows.map(({p,v})=>el('option',{value:p.id+'|'+v.id},p.name+' — '+variantLabel(v.type))));s.value=value;};
 const format=select('مقاس التصميم','marketing-format',[['post','بوست · 1080 × 1350'],['story','ستوري · 1080 × 1920']]);
 const headline=field('عنوان قصير على الصورة','marketing-title','text','متاح الآن',{maxlength:45});
 const caption=field('إعلان تيليجرام — أكمل الحجم والحالة والتسليم قبل النشر','marketing-caption','textarea','',{rows:14});
 const file=field('صورة بديلة للتصميم فقط (اختياري)','marketing-file','file','',{accept:'image/*'});
 const canvas=el('canvas',{width:1080,height:1350,role:'img','aria-label':'معاينة تصميم المنشور',class:'marketing-canvas'});
 const status=el('p',{role:'status',class:'hint'},'اختر عرضاً لبدء التصميم.');let photo=null,logo=null,ready=false,sequence=0;
 const selected=()=>saleEntries(currentState.products).find(x=>x.status==='live'&&x.p.id+'|'+x.v.id===choices.querySelector('select').value);
 const input=caption.querySelector('textarea');
 const linkFor=p=>'https://temoplants.netlify.app/shop?product='+encodeURIComponent(p.id);
 function defaultText(){const x=selected();if(!x)return;input.value=`نموذج بيع نبات\n\n🌱 اسم النبات: ${x.p.name} — ${variantLabel(x.v.type)}\n🔢 العدد: 1\n📏 الحجم: [أدخل الحجم أو الارتفاع التقريبي]\n\n✅ الحالة العامة: [أدخل حالة القطعة]\n💰 السعر: ${formatMoney(x.v.price)} للقطعة\n📍 المدينة: مكة\n🚚 طريقة التسليم (شحن): [أدخل التفاصيل]\n\n📷 صورة النبات والتفاصيل:\n${linkFor(x.p)}`;}
 function text(ctx,value,y,size=42,max=940){ctx.font=`bold ${size}px Arial`;ctx.fillStyle='#171717';ctx.textAlign='center';ctx.direction='inherit';const words=value.split(/\s+/);let line='',lines=[];for(const w of words){if(ctx.measureText(line+' '+w).width>max&&line){lines.push(line);line=w;}else line+=(line?' ':'')+w;}lines.push(line);for(const l of lines){ctx.fillText(l,540,y);y+=size*1.3;}return y;}
 function draw(){const x=selected();ready=false;download.disabled=true;const h=format.querySelector('select').value==='story'?1920:1350;canvas.height=h;const c=canvas.getContext('2d');c.fillStyle='#faf7f3';c.fillRect(0,0,1080,h);if(!x||!photo)return;
 c.fillStyle='#ae0000';c.fillRect(0,0,1080,14);if(logo)c.drawImage(logo,850,45,145,145);c.font='bold 48px Arial';c.textAlign='left';c.fillStyle='#ae0000';c.fillText('Temo_plants',70,112);c.font='28px Arial';c.fillStyle='#555';c.fillText('@temo_plants',70,155);
 const top=220,bottom=h-405,boxH=bottom-top;c.fillStyle='#eee9e3';c.fillRect(55,top,970,boxH);const scale=Math.min(970/photo.width,boxH/photo.height);c.drawImage(photo,55+(970-photo.width*scale)/2,top+(boxH-photo.height*scale)/2,photo.width*scale,photo.height*scale);
 let y=text(c,headline.querySelector('input').value,bottom+55,32);y=text(c,x.p.name,y+24,40);y=text(c,variantLabel(x.v.type)+' · '+formatMoney(x.v.price),y+18,34);
 c.fillStyle='#ae0000';c.fillRect(55,h-115,970,65);c.fillStyle='#fff';c.textAlign='center';c.font='bold 29px Arial';c.fillText('اطلب من المتجر · temoplants.netlify.app',540,h-73);ready=true;download.disabled=false;status.textContent='التصميم جاهز. الصورة كاملة دون قص؛ رابط الطلب موجود في نص المنشور.';}
 async function loadImage(src){return new Promise((resolve,reject)=>{const im=new Image();const timer=setTimeout(()=>reject(new Error('استغرق تحميل الصورة وقتاً طويلاً. اختر صورة من جهازك.')),15000);im.crossOrigin='anonymous';im.onload=()=>{clearTimeout(timer);resolve(im);};im.onerror=()=>{clearTimeout(timer);reject(new Error('تعذر تحميل الصورة. اختر صورة من جهازك لإكمال التصميم.'));};im.src=src;});}
 async function refresh(){const token=++sequence;ready=false;download.disabled=true;photo=null;draw();const x=selected();if(!x)return;status.textContent='جارٍ تجهيز الصورة…';try{const f=file.querySelector('input').files[0];if(f&&f.size>20*1024*1024)throw new Error('اختر صورة أقل من 20MB.');if(!f&&!x.p.image)throw new Error('النبتة بلا صورة. اختر صورة من جهازك للتصميم.');let url=f?URL.createObjectURL(f):x.p.image;try{const im=await loadImage(url);if(token!==sequence)return;photo=im;}finally{if(f)URL.revokeObjectURL(url);}if(!logo)logo=await loadImage('brand-logo.jpeg');if(token===sequence)draw();}catch(e){if(token===sequence){status.textContent=e.message;ready=false;download.disabled=true;}}}
 const download=btn('تحميل التصميم PNG',async()=>{if(!ready||!selected())throw new Error('اختر عرضاً متاحاً وأكمل تحميل الصورة أولاً.');try{draw();const blob=await new Promise((resolve,reject)=>canvas.toBlob(b=>b?resolve(b):reject(new Error('تعذر إنشاء الصورة.')),'image/png'));const url=URL.createObjectURL(blob),a=el('a',{href:url,download:'temo-'+format.querySelector('select').value+'.png'});a.click();setTimeout(()=>URL.revokeObjectURL(url),60000);notice('تم تجهيز التحميل. انشر الصورة وأرفق نص الطلب.');}catch{throw new Error('تعذر تصدير هذه الصورة. اختر نسخة من جهازك ثم أعد المحاولة.');}},'button primary');download.disabled=true;
 choices.addEventListener('change',()=>{file.querySelector('input').value='';defaultText();refresh();});file.addEventListener('change',refresh);format.addEventListener('change',draw);headline.addEventListener('input',draw);
 view=el('section',{class:'stack marketing-studio'},el('link',{rel:'stylesheet',href:'marketing.css'}),el('h1',{},'مركز التسويق'),el('p',{class:'muted'},'صورة حقيقية، شعارك، وسعر البيع. جهّز المحتوى وحمّله للنشر بنفسك — دون رصيد ذكاء اصطناعي.'),el('div',{class:'two-col'},el('div',{class:'panel stack'},choices,format,headline,file,el('p',{class:'hint'},'تظهر العروض المنشورة ذات الكمية المتاحة فقط. الصورة البديلة لا تغيّر صورة النبتة في الموقع.'),caption,el('div',{class:'actions'},btn('نسخ نص المنشور',async()=>{if(!input.value.trim())throw new Error('اختر نبتة أو اكتب النص أولاً.');try{await navigator.clipboard.writeText(input.value);notice('تم نسخ النص.');}catch{input.focus();input.select();notice('حددنا النص؛ انسخه من قائمة الجهاز.',true);}}),btn('استعادة النص الجاهز',defaultText))),el('div',{class:'panel stack'},canvas,status,download)),el('details',{},el('summary',{},'فكرة ريلز بسيطة — قالب تصوير'),el('p',{},'1. لقطة قريبة للورقة (3 ثوانٍ). 2. إظهار القطعة المعروضة كاملة (4 ثوانٍ). 3. عرض الصنف والسعر (3 ثوانٍ). 4. بطاقة ختامية تدعو للطلب من رابط المتجر. استخدم تصوير القطعة الحقيقية، ثم أضف النص أثناء المونتاج.')));
 draw();return [view];
}
