import {el,btn,field,select,check,dialog,notice,table} from './ui.js';
import * as D from './domain.js';
import * as store from './store.js';
import * as api from './service.js';
import {estimate,market,forms,stages,safeURL} from './market-domain.js';
const country=[['SA','السعودية'],['KW','الكويت'],['TH','تايلند'],['CN','الصين'],['VN','فيتنام'],['US','الولايات المتحدة'],['NL','هولندا'],['DE','ألمانيا'],['FR','فرنسا'],['GB','بريطانيا'],['OTHER','بلد آخر (أدخل رمز ISO)']];
const currencies=['SAR','KWD','THB','CNY','VND','EUR','USD','GBP'].map(c=>[c,c]);
export function marketDialog(p,selected){
 let comparisons=[],result=null,serial=0,busy=false,reportSaved=false;
 const err=el('p',{role:'alert',class:'form-error'}),out=el('div',{class:'market-result','aria-live':'polite'}),cards=el('div',{class:'stack'}),history=el('div',{class:'stack'});
 const variant=select('الصنف المسجل','variant',p.variants.filter(v=>!D.variantHidden(v)).map(v=>[v.id,v.type]),selected?.id||p.variants[0]?.id);
 const details=el('div',{class:'form-grid'},variant,field('الاسم العلمي / الهجين','name','text',p.name,{maxlength:200}),select('شكل القطعة','form',forms,'baby'),field('اسم الصنف المخصص (عند اختياره)','custom'),field('الحجم / عدد الأوراق','size','text',p.size||'',{maxlength:200}),select('مرحلة النمو','stage',stages),field('الجذور والتأقلم والصحة','condition','text','',{maxlength:300}),field('التبرقش ومدى ثباته الموثق','variegation','text','',{maxlength:300}),field('الكورمة: الحجم / الكتنج: عقدة وجذور وورقة','structure','text','',{maxlength:300}),check('أؤكد الاسم والصنف؛ الصورة وحدها لا تثبت الهوية','identityConfirmed'),field('صورة حديثة اختيارية — للمرجع المحلي','photo','file','',{accept:'image/png,image/jpeg,image/webp'}));
 const value=(box,n)=>box.querySelector('[name="'+n+'"]').value.trim();
 const input=()=>({productId:p.id,variantId:value(details,'variant'),name:value(details,'name'),form:value(details,'form'),custom:value(details,'form')==='custom'?value(details,'custom'):'',size:value(details,'size'),stage:value(details,'stage'),condition:value(details,'condition'),variegation:value(details,'variegation'),structure:value(details,'structure'),identityConfirmed:details.querySelector('[name=identityConfirmed]').checked});
 function infer(){const v=p.variants.find(v=>v.id===value(details,'variant'));const t=v?.type||'';details.querySelector('[name=form]').value=/كورم|corm/i.test(t)?'corm':/كتنج|cutting/i.test(t)?'cutting':/أم|مذر|mother/i.test(t)?'mother':/شتل|baby|seedling/i.test(t)?'baby':'custom';details.querySelector('[name=custom]').value=details.querySelector('[name=form]').value==='custom'?t:'';}
 infer();variant.addEventListener('change',infer);
 function invalidate(){serial++;result=null;reportSaved=false;out.replaceChildren(el('p',{class:'hint'},'اضغط «احسب التقدير» بعد مراجعة المدخلات والمقارنات.'));}
 details.addEventListener('input',invalidate);
 const preview=el('img',{class:'market-photo',hidden:''});details.append(preview);let photoURL;
 details.querySelector('[name=photo]').addEventListener('change',e=>{if(photoURL)URL.revokeObjectURL(photoURL);const f=e.target.files[0];preview.hidden=true;if(!f)return;if(f.size>5*1024*1024){err.textContent='الحد للصورة 5MB.';e.target.value='';return;}photoURL=URL.createObjectURL(f);preview.src=photoURL;preview.hidden=false;});
 document.getElementById('dialog').addEventListener('close',()=>{if(photoURL)URL.revokeObjectURL(photoURL);},{once:true});
 function addComparison(seed={}){
  if(comparisons.length>=20)throw new Error('الحد 20 مقارنة في التقدير.');
  const i=input(),r={...seed},box=el('details',{class:'market-comparison',open:''});
  const body=el('div',{class:'form-grid'},field('المصدر / البائع','seller','text',r.seller||'',{maxlength:150}),field('رابط الإعلان HTTPS','url','url',r.url||'',{maxlength:1500}),field('تاريخ السعر / الإعلان','date','date',r.date||''),field('الاسم العلمي في الإعلان','name','text',r.name||i.name),select('شكل القطعة','form',forms,r.form||i.form),field('الصنف المخصص','custom','text',r.custom||i.custom),select('مرحلة النمو','stage',stages,r.stage||i.stage),field('وصف القطعة وحجمها وحالتها','description','textarea',r.description||'',{maxlength:1000}),select('بلد البائع','country',country,r.country||market.country),field('رمز البلد الآخر (حرفان)','otherCountry','text','',{maxlength:2}),field('سعر الإعلان','price','number',r.price??'',{min:0,step:'any'}),field('عدد القطع المشمولة بالسعر','units','number',r.units??1,{min:1,step:1}),select('العملة','currency',currencies,r.currency||market.currency),select('نوع الإعلان','saleType',[['retail','تجزئة'],['wholesale','جملة'],['auction','مزاد']],r.saleType||'retail'),select('حالة السعر','status',[['asking','سعر عرض'],['sold','بيع مكتمل']],r.status||'asking'),check('يوجد دليل صريح على إتمام البيع بالسعر المذكور','soldEvidence',false),select('تطابق الحجم والحالة والتبرقش','match',[['unknown','لم أتحقق'],['exact','متطابق / قابل للمقارنة'],['different','مختلف']],r.match||'unknown'),check('راجعت المصدر والسعر والعملة والتاريخ وتطابق القطعة','reviewed',false),field('صورة إعلان بدلاً من الرابط (تُحفظ خاصة مع التقدير)','evidence','file','',{accept:'image/jpeg,image/png,image/webp'}));
  const extra=el('details',{class:'full'},el('summary',{},'سعر الصرف وتكلفة الوصول — بالريال السعودي للقطعة'),el('div',{class:'form-grid'},field('ريال لكل وحدة من العملة الأجنبية','fx','number',r.fx??'',{min:0,step:'any'}),field('تاريخ سعر الصرف','fxDate','date',r.fxDate||''),field('مصدر سعر الصرف HTTPS','fxSource','url',r.fxSource||''),...['shipping','duties','permits','acclimation'].map((k,j)=>field(['شحن القطعة','رسوم وجمارك القطعة','تصاريح القطعة','تأقلم القطعة'][j]+' — فارغ = غير معروف',k,'number','',{min:0,step:'.01'}))));body.append(extra);
  box.append(el('summary',{},r.origin==='ai'?'مقارنة من البحث — تحتاج مراجعتك':'مقارنة مقدمة منك'),body,btn('إزالة المقارنة',()=>{box.remove();comparisons=comparisons.filter(x=>x.box!==box);invalidate();},'button subtle'));
  const entry={box,read(){const o={origin:r.origin||'manual',observedAt:r.observedAt||new Date().toISOString(),quote:r.quote||'',evidenceData:entry.evidenceData||'',evidenceId:entry.evidenceData?entry.evidenceId:''};for(const n of ['seller','url','date','name','form','custom','stage','description','country','currency','saleType','status','match','fxDate','fxSource'])o[n]=value(body,n);if(o.form!=='custom')o.custom='';if(o.country==='OTHER')o.country=value(body,'otherCountry').toUpperCase();for(const n of ['price','units','fx','shipping','duties','permits','acclimation'])o[n]=value(body,n)===''?null:Number(value(body,n));for(const n of ['reviewed','soldEvidence'])o[n]=body.querySelector('[name='+n+']').checked;return o;}};
  body.querySelector('[name=evidence]').addEventListener('change',async e=>{try{entry.evidenceData='';const f=e.target.files[0];if(!f)return;if(!['image/jpeg','image/png','image/webp'].includes(f.type)||f.size>100000)throw new Error('صورة الإعلان يجب أن تكون JPG/PNG/WebP وأصغر من 100KB؛ استخدم الرابط للصورة الأكبر.');entry.evidenceData=await new Promise((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(reader.result);reader.onerror=reject;reader.readAsDataURL(f);});entry.evidenceId=D.id();invalidate();}catch(e){err.textContent=e.message;}});
  const suffix=D.id();body.querySelectorAll('[id]').forEach(n=>{const old=n.id;n.id=old+'-'+suffix;body.querySelectorAll('label').forEach(l=>{if(l.htmlFor===old)l.htmlFor=n.id;});});body.addEventListener('input',invalidate);comparisons.push(entry);cards.append(box);invalidate();
 }
 function calculate(){err.textContent='';const i=input();if(!i.name||!i.identityConfirmed)throw new Error('أكّد هوية النبات واكتب الاسم أولاً.');result=estimate(i,comparisons.map(x=>x.read()));reportSaved=false;showResult();}
 function showResult(){
  const r=result;
  const sections=['local','foreign','excluded'].map((k,j)=>el('section',{},
   el('h4',{},['المقارنات المحلية','الأسواق الخارجية — لا تحدد السعر المحلي وحدها','مقارنات مستبعدة'][j]),
   table(['المصدر','القطعة / التاريخ','السعر','الملاحظة'],r[k].map(x=>[
    safeURL(x.url)?el('a',{href:safeURL(x.url),target:'_blank',rel:'noopener noreferrer'},x.seller||'فتح المصدر'):el('span',{},'صورة مقدمة منك'),
    (x.description||x.name)+' · '+x.country+' · '+x.date,
    x.price+' '+x.currency+' / '+x.units+' قطعة',
    x.why||(x.country!==market.country?'تكلفة الوصول: '+(x.landed===null?'غير مكتملة':D.formatMoney(Math.round(x.landed*market.scale))):'مطابقة ومراجعة')
   ]))));
  out.replaceChildren(...[
   el('h3',{},r.range?'النطاق المتوقع: '+r.range.map(D.formatMoney).join(' – '):'البيانات غير كافية لتقدير موثوق'),
   el('p',{},'الثقة: '+r.confidence+' · '+r.local.length+' مقارنة محلية · '+r.foreign.length+' خارجية'),
   el('p',{class:'hint'},'تاريخ الحساب: '+r.createdAt),...r.reasons.map(x=>el('p',{class:'hint'},x)),
   r.median!==null?el('p',{},'السعر المعتاد المقترح: '+D.formatMoney(r.median)):null,
   el('p',{},r.quick?'نطاق منخفض مستند إلى مبيعات مكتملة (لا يضمن سرعة البيع): '+r.quick.map(D.formatMoney).join(' – '):'لا تتوفر أدلة كافية لنطاق بيع سريع.'),
   ...sections,btn('حفظ التقدير',save,'button primary'),r.median!==null?btn('استخدام السعر المقترح',apply):null].filter(Boolean));
 }
 async function save(){if(!result||reportSaved)return;if(JSON.stringify(result).length>650000)throw new Error('صور المقارنات كبيرة؛ قلل عددها قبل الحفظ.');const id=D.id(),record={id,kind:'market-estimate',productId:p.id,createdAt:new Date().toISOString(),uid:store.uid(),report:result};await store.atomic(['audit/'+id],()=>({writes:{['audit/'+id]:record}}));reportSaved=true;notice('حُفظ التقدير في سجل الإدارة الخاص.');await loadHistory();}
 async function apply(){if(!result?.median)return;const r=result;if(!confirm('تغيير سعر الصنف المحدد فقط إلى '+D.formatMoney(r.median)+'؟ لن تتغير حالة عرضه أو المخزون.'))return;const fresh=await store.get('products/'+p.id);D.assert(fresh&&fresh.revision===p.revision,'تغيرت النبتة. أغلق النافذة وأعد فتحها.');await api.saveProduct({...fresh,variants:fresh.variants.map(v=>v.id===r.input.variantId?{...v,price:r.median}:v)});notice('تم تحديث سعر الصنف بعد تأكيدك.');document.getElementById('dialog').close();}
 async function search(refresh=false){if(busy)return;const i=input();if(!i.identityConfirmed||!i.name)throw new Error('أكّد هوية النبات أولاً.');if(store.demo)throw new Error('البحث الحي غير متصل في المعاينة. أضف مقارناتك يدوياً لتجربة الحساب.');busy=true;const ticket=serial;searchButton.disabled=true;err.textContent='جارٍ البحث في المصادر المتاحة…';try{const token=await store.marketToken();const response=await fetch('/.netlify/functions/market-estimate',{method:'POST',headers:{'Content-Type':'application/json',Authorization:'Bearer '+token},body:JSON.stringify({input:i,refresh}),signal:AbortSignal.timeout(60000)});if(!response.headers.get('content-type')?.includes('application/json'))throw new Error('خدمة البحث لم تُنشر بعد. يمكنك استخدام المقارنات اليدوية الآن.');const data=await response.json();if(!response.ok)throw new Error(data.error||'تعذر البحث.');if(ticket!==serial)throw new Error('تغيرت المدخلات أثناء البحث؛ أعد البحث للصنف الجديد.');for(const r of data.comparisons||[])addComparison(r);err.textContent='آخر بحث: '+data.searchedAt+(data.cached?' (محفوظ مؤقتاً)':'')+' — '+(data.message||'راجع المصادر قبل حساب التقدير.');}catch(e){err.textContent=e.name==='TimeoutError'?'انتهت مهلة البحث؛ مدخلاتك محفوظة. حاول لاحقاً.':e.message;}finally{busy=false;searchButton.disabled=false;}}
 async function loadHistory(){const rows=(await store.list('audit')).filter(x=>x.kind==='market-estimate'&&x.productId===p.id).sort((a,b)=>b.createdAt.localeCompare(a.createdAt)).slice(0,5);history.replaceChildren(...rows.map(x=>btn('تقدير محفوظ · '+x.createdAt.slice(0,16),()=>{dialog('تقدير سابق — للقراءة',el('div',{class:'stack'},el('p',{},x.report.input.name+' · '+x.report.input.form),el('p',{},x.report.range?x.report.range.map(D.formatMoney).join(' – '):'بيانات غير كافية'),el('p',{},x.report.reasons.join(' ')),table(['المصدر','التاريخ','السعر'],[...x.report.local,...x.report.foreign].map(r=>[safeURL(r.url)?el('a',{href:safeURL(r.url),target:'_blank',rel:'noopener'},r.seller||'المصدر'):'صورة محفوظة',r.date,r.price+' '+r.currency]))));})));}
 const searchButton=btn('بحث حي بالذكاء الاصطناعي',()=>search(),'button');
 const content=el('div',{class:'stack market-dialog'},el('p',{class:'hint'},'تقدير خاص بالإدارة · السعودية / SAR. لا يتغير سعر البيع إلا بعد تأكيدك. الصور المحلية لا تُرسل إلى مزود البحث؛ يُرسل وصف النبتة فقط.'),details,el('div',{class:'actions'},searchButton,btn('تحديث البحث',()=>search(true)),btn('+ إضافة إعلان / مقارنة يدوية',()=>addComparison())),err,cards,btn('احسب التقدير',calculate,'button primary'),out,el('details',{},el('summary',{},'آخر التقديرات المحفوظة'),history));
 dialog('تقدير سعر السوق ✨ — '+p.name,content);loadHistory().catch(e=>{err.textContent=e.message;});
}
