import * as D from './domain.js';
import {el,btn,moneyNode} from './ui.js';
import {variantLabel} from './storefront-content.js';
export function plantPage(p,state,actions){
 if(!p)return [el('h1',{},'النبتة غير موجودة'),btn('العودة إلى نباتاتي',actions.back)];
 const variants=p.variants.filter(v=>!D.variantHidden(v));
 const section=(title,...nodes)=>el('section',{class:'panel stack'},el('h2',{},title),...nodes);
 const image=D.safeImage(p.image);
 const movements=state.movements.filter(m=>m.productId===p.id).sort((a,b)=>String(b.at||b.date).localeCompare(String(a.at||a.date)));
 const orders=state.orders.filter(o=>o.items.some(i=>i.productId===p.id)).sort((a,b)=>String(b.createdAt||b.date).localeCompare(String(a.createdAt||a.date)));
 const purchases=state.purchases.filter(x=>x.productId===p.id);
 const kinds={purchase:'شراء',opening:'رصيد افتتاحي',production:'إنتاج',loss:'تلف / فقد',reserve:'حجز',sell:'بيع',fulfill:'تحويل الحجز إلى بيع',cancel:'إلغاء الحجز',return:'مرتجع'};
 const status={reserved:'محجوز',sold:'مباع',cancelled:'ملغي',returned:'مرتجع'};
 return [btn('→ العودة إلى نباتاتي',actions.back,'button subtle'),el('div',{class:'page-head'},el('div',{},el('p',{class:'eyebrow'},p.code+' · '+p.genus),el('h1',{},p.name),el('p',{class:'muted'},'ملف النبتة · المجموعة والإنتاج وعروض البيع')),btn('تعديل البيانات والصورة',()=>actions.edit(p))),
 el('div',{class:'plant-hub'},
 section('الصورة والتفاصيل',image?el('img',{class:'plant-hub-image',src:image,alt:p.name,loading:'lazy',width:'640',height:'640',onError:e=>{e.target.hidden=true;}}):el('p',{class:'empty'},'أضف صورة للنبتة من تعديل البيانات والصورة.'),el('p',{class:'hint'},p.actualPhoto?'الصورة للقطعة الفعلية':'الصورة تمثيلية',p.photoDate?' · '+p.photoDate:''),el('p',{},p.size||'الحجم غير مسجل'),el('p',{},p.publicDescription||'لم يُضف وصف للمتجر بعد.'),p.care?el('p',{},'العناية: '+p.care):null,el('details',{},el('summary',{},'ملاحظاتك الداخلية'),el('p',{},p.internalNotes||'لا توجد ملاحظات.'))),
 section('ماذا تريد أن تفعل؟',el('div',{class:'plant-hub-actions'},btn('إضافة إنتاج',()=>actions.production(p),'button primary'),btn('تسجيل شراء إضافي',()=>actions.purchase(p)),btn('تقدير سعر السوق',()=>actions.price(p))),el('p',{class:'hint'},'الإنتاج يضيف كورمات أو كتنج دون استهلاك الأم. الشراء يسجل كمية وتكلفة جديدة.'),el('h3',{},'الأصناف والمخزون'),...variants.map(v=>el('article',{class:'plant-hub-variant'},el('h3',{},variantLabel(v.type)),el('div',{class:'row'},el('span',{},'الموجود: '+v.qty),el('span',{},'المحجوز: '+v.reserved),el('strong',{},'المتاح: '+D.available(v))),el('div',{class:'row'},el('span',{},v.sell?(p.published?'مفعّل للعرض في المتجر':'عرض مسودة'):'ضمن المجموعة — غير معروض'),moneyNode(v.price)),el('div',{class:'actions'},btn('إعداد عرض هذا الصنف',()=>actions.offer(p,v)),v.sell&&D.available(v)>0?btn('تسجيل بيع',()=>actions.sell({...p,variants:[v]})):null))),el('p',{class:'hint'},'لعرض الإنتاج فقط، فعّل الكورمة أو الكتنج واترك صنف الأم غير معروض.'))),
 section('سجل العمليات',el('p',{class:'muted'},movements.length+' حركة · '+purchases.length+' عملية شراء · '+orders.length+' طلب'),el('div',{class:'plant-history'},...(movements.length?movements.map(m=>el('article',{class:'plant-history-row'},el('div',{class:'row'},el('strong',{},kinds[m.kind]||m.kind),el('time',{},m.date||String(m.at||'').slice(0,10))),el('p',{},(p.variants.find(v=>v.id===m.variantId)?.type||'صنف سابق')+' · الكمية: '+m.qty),el('p',{class:'hint'},m.reason||''))):[el('p',{class:'empty'},'لا توجد حركات مسجلة لهذه النبتة.')]))),
 section('الطلبات المرتبطة بالنبتة',...(orders.length?orders.map(o=>el('article',{class:'plant-history-row'},el('div',{class:'row'},el('strong',{},o.number),el('span',{class:'tag'},status[o.status]||o.status)),el('p',{},o.customer+' · '+o.date),...o.items.filter(i=>i.productId===p.id).map(i=>el('p',{},i.type+' × '+i.qty+' — '+D.formatMoney(i.qty*i.price))),btn('فتح الطلب',()=>actions.order(o)))):[el('p',{class:'empty'},'لا توجد طلبات مرتبطة بعد.')])),
 section('المشتريات والتكاليف',...(purchases.length?purchases.map(x=>el('article',{class:'plant-history-row'},el('div',{class:'row'},el('strong',{},x.date),moneyNode(x.total)),el('p',{},'الكمية: '+x.qty+' · المورد: '+(x.supplier||'غير مسجل')))):[el('p',{class:'empty'},'لا توجد مشتريات مسجلة. الرصيد الافتتاحي يظهر في سجل العمليات.')]))];
}
