import * as store from './store.js';
import * as D from './domain.js';
import {shopSettings} from './config.js';
import {genusKey,genusSearch,searchKey,genera} from './catalog-fields.js';
import {genusDetails,variantLabel,availableVariants as variants,inquiryText} from './storefront-content.js';
import {$,el,btn,notice,errorText} from './ui.js';
let products=[],activeId=new URLSearchParams(location.search).get('product'),selectedVariant='',selectedQty=1,ready=false;
const home='shop.html'+(store.demo?'?demo=1':'');
const href=id=>home+(store.demo?'&':'?')+'product='+encodeURIComponent(id);
const instagram='https://ig.me/m/'+encodeURIComponent(shopSettings.instagram);
function placeholder(){return el('span',{class:'plant-placeholder'},el('img',{src:'brand-logo.jpeg',alt:'Temo_plants',width:'100',height:'100'}),el('small',{},'صورة النبات قريباً'));}
function image(p){const src=D.safeImage(p.image);if(!src)return placeholder();const n=el('img',{src,alt:p.name,loading:'lazy',decoding:'async',width:'800',height:'800'});n.addEventListener('error',()=>n.replaceWith(placeholder()));return n;}
function showProduct(id,push=true){activeId=id;selectedVariant='';selectedQty=1;if(push)history.pushState({},'',href(id));render();$('main').focus();scrollTo({top:0,behavior:'smooth'});}
function updateMeta(p){document.title=p?p.name+' | Temo Plants':'Temo Plants — نباتات نادرة';document.querySelector('meta[name="description"]').content=p?(p.description||p.name).slice(0,160):'كل ورقة تحكي شغف. نباتات نادرة وزراعة مائية من السعودية — Alocasia · Anthurium · Hoya.';let canonical=document.querySelector('link[rel=canonical]');if(shopSettings.canonicalBase){if(!canonical){canonical=el('link',{rel:'canonical'});document.head.append(canonical);}canonical.href=shopSettings.canonicalBase+'/shop.html'+(p?'?product='+encodeURIComponent(p.id):'');}}
function genusInfo(g){const info=genusDetails[genusKey(g)];return info?el('section',{class:'panel genus-info'},el('h2',{},info.title),el('p',{},info.text)):null;}
function card(p){const a=el('a',{href:href(p.id),class:'product-visual','aria-label':'عرض '+p.name,onClick:e=>{e.preventDefault();showProduct(p.id);}},image(p),el('span',{class:'tag'},genusSearch(p.genus)));return el('article',{class:'product-card'},a,el('div',{class:'product-content'},el('div',{class:'product-code'},p.code),el('h3',{},p.name),el('p',{class:'muted'},variants(p).map(v=>variantLabel(v.type)).join(' · ')),el('a',{href:href(p.id),class:'button',onClick:e=>{e.preventDefault();showProduct(p.id);}},'التفاصيل والاستفسار ↗')));}
function render(){if(activeId){detail();return;}$('hero').hidden=false;$('catalog-view').hidden=false;$('product-view').hidden=true;updateMeta(null);const q=searchKey($('search').value),g=$('genus').value;let list=products.filter(p=>p.published&&variants(p).length&&(!g||genusKey(p.genus)===g)&&searchKey([p.name,p.code,genusSearch(p.genus)].join(' ')).includes(q));list.sort((a,b)=>$('sort').value==='recent'?String(b.updatedAt||'').localeCompare(String(a.updatedAt||'')):a.name.localeCompare(b.name));$('count').textContent=list.length+' نبات';$('genus-info').replaceChildren(...(g?[genusInfo(g)].filter(Boolean):[el('p',{class:'muted'},'اختر النوع للتعرف على المجموعة وتصفح النباتات المتاحة.') ]));$('catalog').replaceChildren(...(list.length?list.map(card):[el('div',{class:'empty'},'لا توجد نباتات مطابقة الآن.',btn('عرض الكل',()=>{$('search').value='';$('genus').value='';render();}))]));}
function detail(){const p=products.find(p=>p.id===activeId&&p.published);$('hero').hidden=true;$('catalog-view').hidden=true;$('product-view').hidden=false;const back=el('a',{href:home,class:'button subtle',onClick:e=>{e.preventDefault();activeId=null;history.pushState({},'',home);render();}},'→ العودة للمجموعة');if(!p){$('product-view').replaceChildren(back,el('div',{class:'empty'},ready?'هذا النبات غير معروض حالياً.':'جارٍ تحميل تفاصيل النبتة…'));updateMeta(null);return;}
 updateMeta(p);const vs=variants(p);if(!vs.some(v=>v.id===selectedVariant))selectedVariant=vs[0]?.id||'';
 const variantSelect=el('select',{id:'variant','aria-label':'اختيار الصنف'},vs.map(v=>el('option',{value:v.id,...(v.id===selectedVariant?{selected:''}:{})},variantLabel(v.type))));
 const q=el('input',{id:'qty',type:'number',min:'1',step:'1',value:String(selectedQty),'aria-label':'الكمية المطلوبة'}),msg=el('p',{class:'hint',role:'status'});let manual=false;
 const inquire=btn('استفسار عن تفاصيل الطلب عبر الانستجرام',async()=>{try{D.assert(ready,'تعذر تحديث التوفر. حدّث الصفحة قبل الطلب.');const fresh=products.find(x=>x.id===p.id);D.assert(fresh,'هذا النبات غير متاح حالياً.');const text=inquiryText(fresh,variantSelect.value,q.value,location.href);if(!manual){try{await navigator.clipboard.writeText(text);}catch{const box=el('textarea',{'aria-label':'نص الاستفسار للنسخ',readonly:'',rows:'9'});box.value=text;msg.replaceChildren('تعذر النسخ التلقائي. انسخ النص أدناه، ثم اضغط زر الاستفسار مجدداً لفتح Instagram.',box);box.select();manual=true;return;}}notice(manual?'ألصق تفاصيل الطلب في Instagram وأرسلها بعد المراجعة.':'نُسخ الطلب. ألصقه في محادثة Instagram وأرسله بعد المراجعة.');const win=window.open(instagram,'_blank');if(win)win.opener=null;else location.assign(instagram);}catch(e){notice(errorText(e),true);}},'button primary');
 function update(){manual=false;selectedVariant=variantSelect.value;selectedQty=Number(q.value)||1;inquire.disabled=!vs.length;msg.textContent=vs.length?'متاح للاستفسار. السعر وحالة القطعة والشحن تؤكد عبر Instagram.':'غير متوفر حالياً.';}
 variantSelect.addEventListener('change',update);q.addEventListener('input',update);update();
 $('product-view').replaceChildren(back,el('article',{class:'product-detail'},el('div',{},el('div',{class:'detail-image'},image(p)),el('p',{class:'hint'},p.image?(p.actualPhoto?'الصورة للقطعة الفعلية.':'الصورة تمثيلية؛ اطلب صورة القطعة قبل الشراء.'):'اطلب صور القطعة قبل تأكيد الطلب.',p.photoDate?' آخر تصوير: '+p.photoDate:'')),el('div',{class:'stack'},el('div',{class:'eyebrow'},genusSearch(p.genus)+' / '+p.code),el('h1',{class:'detail-name'},p.name),el('p',{},p.description||'راسلنا لمعرفة تفاصيل هذه النبتة وحالتها.'),p.size?el('p',{},'الحجم والحالة: '+p.size):null,p.care?el('p',{class:'muted'},'العناية: '+p.care):null,genusInfo(p.genus),el('label',{class:'field',for:'variant'},'الصنف / Plant form',variantSelect),el('label',{class:'field',for:'qty'},'الكمية المطلوبة',q),msg,inquire,el('p',{class:'hint'},'الزر ينسخ تفاصيل الطلب ويفتح Instagram. ألصق النص في المحادثة؛ لا يُرسل تلقائياً ولا يحجز الكمية.'))));
}
$('demo-banner').hidden=!store.demo;$('home-link').href=home;$('shipping-policy').textContent=shopSettings.shipping;$('return-policy').textContent=shopSettings.returns;
for(const n of ['search','genus','sort'])$(n).addEventListener(n==='search'?'input':'change',render);
addEventListener('popstate',()=>{activeId=new URLSearchParams(location.search).get('product');render();});
try{await store.connect();store.subscribe('publicProducts',rows=>{products=rows;ready=true;const g=$('genus').value,keys=[...new Set([...genera.map(([x])=>genusKey(x)),...products.filter(p=>p.published).map(p=>genusKey(p.genus))])];$('genus').replaceChildren(el('option',{value:''},'كل الأنواع'),...keys.map(g=>el('option',{value:g},genusSearch(g))));$('genus').value=keys.includes(g)?g:'';render();},e=>{ready=false;notice('تعذر تحديث التوفر. أعد المحاولة قبل الطلب.',true);$('catalog').replaceChildren(el('div',{class:'empty'},errorText(e),btn('إعادة المحاولة',()=>location.reload())));});}catch(e){ready=false;$('catalog').replaceChildren(el('div',{class:'empty'},errorText(e)));notice(errorText(e),true);}
