import {initCheckout,addToCart,openCart,formatShopMoney} from './shop-checkout.js';
import * as store from './store.js';
import * as D from './domain.js';
import {shopSettings} from './config.js';
import {genusKey,genusSearch,searchKey,genera} from './catalog-fields.js';
import {genusDetails,variantLabel,availableVariants as variants} from './storefront-content.js';
import {$,el,btn,notice,errorText,setupDialog} from './ui.js';
let products=[],activeId=null,activeGenus='',forceGrid=false,selectedVariant='',selectedQty=1,ready=false,observers=[];
const visible=()=>products.filter(p=>p.published&&variants(p).length);
const home='shop.html'+(store.demo?'?demo=1':'');
function urlFor(id=activeId,g=activeGenus){const u=new URL(location.href);u.searchParams.delete('product');u.searchParams.delete('genus');u.searchParams.delete('view');if(id)u.searchParams.set('product',id);if(g)u.searchParams.set('genus',g);if(forceGrid&&!id)u.searchParams.set('view','all');return u.pathname+u.search+u.hash;}
const href=id=>urlFor(id);
function readURL(){const u=new URLSearchParams(location.search);activeId=u.get('product');activeGenus=genusKey(u.get('genus')||'');forceGrid=u.get('view')==='all';}
const motion=()=>matchMedia('(prefers-reduced-motion: reduce)').matches?'instant':'smooth';
function remember(){history.replaceState({...history.state,shopView:{y:scrollY,q:$('search').value,sort:$('sort').value,tracks:Object.fromEntries([...document.querySelectorAll('.shelf-track')].map(t=>[t.id,t.scrollLeft]))}},'',location.href);}
function restore(view){if(!view)return;requestAnimationFrame(()=>{for(const [id,x]of Object.entries(view.tracks||{})){const t=$(id);if(t)t.scrollLeft=x;}scrollTo({top:view.y||0,behavior:'instant'});});}
function showProduct(id,push=true){if(push){remember();history.pushState({fromCatalog:!activeId},'',href(id));}activeId=id;selectedVariant='';selectedQty=1;render();$('main').focus({preventScroll:true});scrollTo({top:0,behavior:'instant'});}
function selectGenus(g,all=false){remember();activeId=null;activeGenus=g;forceGrid=all;$('search').value='';if(all)$('sort').value='recent';history.pushState({},'',urlFor(null,g));render();$('catalog-start').scrollIntoView({block:'start',behavior:motion()});}
function updateMeta(p){document.title=p?p.name+' | Temo Plants':'Temo Plants — نباتات نادرة';document.querySelector('meta[name="description"]').content=p?(p.description||p.name).slice(0,160):'كل ورقة تحكي شغف. نباتات نادرة وزراعة مائية من السعودية — Alocasia · Anthurium · Hoya.';let canonical=document.querySelector('link[rel=canonical]');if(shopSettings.canonicalBase){if(!canonical){canonical=el('link',{rel:'canonical'});document.head.append(canonical);}canonical.href=shopSettings.canonicalBase+'/shop.html'+(p?'?product='+encodeURIComponent(p.id):'');}}
function placeholder(){return el('span',{class:'plant-placeholder'},el('img',{src:'brand-logo-d9723ed1a9.webp',alt:'',width:'100',height:'100'}),el('small',{},'صورة النبات قريباً'));}
function image(p){const src=D.safeImage(p.image);if(!src)return placeholder();const n=el('img',{src,alt:p.name,loading:'lazy',decoding:'async',width:'800',height:'1000'});n.addEventListener('error',()=>n.replaceWith(placeholder()),{once:true});return n;}
function genusInfo(g){const info=genusDetails[genusKey(g)];return info?el('section',{class:'panel genus-info'},el('h2',{},info.title),el('p',{},info.text)):null;}
function groups(list){const map=new Map();for(const p of list){const key=genusKey(p.genus);if(!map.has(key))map.set(key,[]);map.get(key).push(p);}const order=genera.map(([g])=>genusKey(g));return [...map].sort(([a],[b])=>{const ia=order.indexOf(a),ib=order.indexOf(b);return (ia<0?999:ia)-(ib<0?999:ib)||a.localeCompare(b);});}
const byName=(a,b)=>Number(!!D.safeImage(b.image))-Number(!!D.safeImage(a.image))||a.name.localeCompare(b.name);
const minPrice=p=>{const prices=variants(p).filter(v=>v.price>0).map(v=>v.price);return prices.length?Math.min(...prices):Infinity;};
function priceLabel(p){const prices=[...new Set(variants(p).map(v=>v.price))],minimum=minPrice(p);return minimum===Infinity?'السعر قيد التحديث':(prices.length>1?'من ':'')+formatShopMoney(minimum);}
function card(p,tag=false){const open=e=>{if(e.button||e.metaKey||e.ctrlKey||e.shiftKey||e.altKey)return;e.preventDefault();showProduct(p.id);},vs=variants(p),single=vs.length===1&&vs[0].price>0;
 const action=btn(single?'أضف للسلة':'اختر الصنف',()=>{if(!single){showProduct(p.id);return;}const fresh=products.find(x=>x.id===p.id);D.assert(ready&&fresh?.published,'تعذر تحديث التوفر؛ أعد تحميل الصفحة.');const current=variants(fresh);D.assert(current.length===1&&current[0].id===vs[0].id,'تغيرت الأصناف؛ افتح النبتة واختر الصنف من جديد.');addToCart(fresh,current[0],1);},single?'button primary':'button');
 return el('article',{class:'product-card'},el('a',{href:href(p.id),class:'product-visual','aria-label':'عرض '+p.name,onClick:open},image(p),tag?el('span',{class:'tag genus-tag'},genusSearch(p.genus)):null,vs.reduce((n,v)=>n+v.available,0)===1?el('span',{class:'last-piece'},'آخر قطعة'):null),el('div',{class:'product-content'},el('h3',{},el('a',{href:href(p.id),onClick:open},p.name)),el('strong',{class:'product-price'},priceLabel(p)),el('p',{class:'variant-line muted',title:vs.map(v=>variantLabel(v.type)).join(' · ')},vs.map(v=>variantLabel(v.type)).join(' · ')),action));}
function shelf(key,title,items,{tag=false,limit=10,all}={}){const heading='shelf-'+key,track=el('div',{class:'shelf-track',id:'track-'+key,role:'list',tabindex:'0','aria-labelledby':heading},items.slice(0,limit).map(p=>el('div',{class:'shelf-item',role:'listitem'},card(p,tag))));if(items.length>limit&&all)track.append(el('div',{class:'shelf-item shelf-more',role:'listitem'},btn('عرض الكل (+'+(items.length-limit)+')',all)));
 const move=sign=>track.scrollBy({left:sign*(getComputedStyle(track).direction==='rtl'?-1:1)*track.clientWidth*.8,behavior:motion()}),prev=btn('›',()=>move(-1),'shelf-nav prev'),next=btn('‹',()=>move(1),'shelf-nav next');prev.setAttribute('aria-label','السابق — '+title);next.setAttribute('aria-label','التالي — '+title);
 const update=()=>{const max=Math.max(0,track.scrollWidth-track.clientWidth),x=Math.abs(track.scrollLeft);prev.disabled=x<=2;next.disabled=x>=max-2;};track.addEventListener('scroll',update,{passive:true});track.addEventListener('keydown',e=>{if(e.target!==track)return;if(e.key==='ArrowLeft'||e.key==='ArrowRight'){e.preventDefault();move(e.key==='ArrowLeft'?1:-1);}});const observer=new ResizeObserver(update);observer.observe(track);observers.push(observer);requestAnimationFrame(update);
 return el('section',{class:'shelf','aria-labelledby':heading},el('div',{class:'shelf-head'},el('h3',{id:heading},title,' ',el('span',{class:'muted'},String(items.length))),all?btn('عرض الكل ‹',all,'shelf-all'):null),el('div',{class:'shelf-wrap'},prev,track,next));}
function chips(list){const options=[['','كل الأنواع',list.length],...groups(list).map(([g,ps])=>[g,genusSearch(g),ps.length])];$('genus-chips').replaceChildren(...options.map(([g,label,n])=>{const b=btn(label+' · '+n,()=>selectGenus(g),'genus-chip');b.setAttribute('aria-pressed',String(activeGenus===g));return b;}));}
function render(){for(const o of observers)o.disconnect();observers=[];document.body.classList.toggle('has-product',!!activeId);if(activeId){detail();return;}$('hero').hidden=false;$('catalog-view').hidden=false;$('product-view').hidden=true;updateMeta(null);const all=visible(),q=searchKey($('search').value),shelves=!q&&!activeGenus&&!forceGrid;chips(all);let list=all.filter(p=>(!activeGenus||q||genusKey(p.genus)===activeGenus)&&searchKey([p.name,p.code,genusSearch(p.genus)].join(' ')).includes(q));const sort=$('sort').value;
 list.sort((a,b)=>sort==='recent'?String(b.updatedAt||'').localeCompare(String(a.updatedAt||''))||byName(a,b):sort.startsWith('price')?(minPrice(a)===Infinity?minPrice(b)===Infinity?byName(a,b):1:minPrice(b)===Infinity?-1:(sort==='price-asc'?1:-1)*(minPrice(a)-minPrice(b))||byName(a,b)):byName(a,b));
 $('count').textContent=list.length+' نبات';$('sort').hidden=shelves;$('catalog-title').textContent=shelves?'اكتشف مجموعتنا':activeGenus&&!q?genusSearch(activeGenus):'نتائج البحث والتصفح';$('genus-info').replaceChildren(...(!shelves&&activeGenus&&!q?[genusInfo(activeGenus)].filter(Boolean):[]));$('catalog').classList.toggle('is-shelves',shelves);
 if(!list.length){$('catalog').replaceChildren(el('div',{class:'empty'},ready?'لا توجد نباتات مطابقة الآن.':'جارٍ تحميل النباتات…',ready?btn('عرض الكل',()=>selectGenus('')):null));return;}
 $('catalog').replaceChildren(...(shelves?[shelf('recent','المضاف والمحدّث حديثًا',[...all].sort((a,b)=>String(b.updatedAt||'').localeCompare(String(a.updatedAt||''))||byName(a,b)).slice(0,8),{tag:true,limit:8,all:()=>selectGenus('',true)}),...groups(all).map(([g,ps])=>shelf('genus-'+g,genusSearch(g),ps.sort(byName),{all:()=>selectGenus(g)}))]:list.map(p=>card(p,!!q||!activeGenus))));}
function detail(){const p=products.find(p=>p.id===activeId&&p.published);$('hero').hidden=true;$('catalog-view').hidden=true;$('product-view').hidden=false;const back=el('a',{href:home,class:'button subtle',onClick:e=>{e.preventDefault();if(history.state?.fromCatalog){history.back();return;}remember();activeId=null;history.pushState({},'',urlFor(null));render();scrollTo({top:0,behavior:'instant'});}},'→ العودة للمجموعة');if(!p){$('product-view').replaceChildren(back,el('div',{class:'empty'},ready?'هذا النبات غير معروض حالياً.':'جارٍ تحميل تفاصيل النبتة…'));updateMeta(null);return;}
 updateMeta(p);const vs=variants(p);if(!vs.some(v=>v.id===selectedVariant))selectedVariant=vs[0]?.id||'';
 const variantSelect=el('select',{id:'variant','aria-label':'اختيار الصنف'},vs.map(v=>el('option',{value:v.id,...(v.id===selectedVariant?{selected:''}:{})},variantLabel(v.type))));
 const q=el('input',{id:'qty',type:'number',min:'1',step:'1',value:String(selectedQty),'aria-label':'الكمية المطلوبة'}),msg=el('p',{class:'hint',role:'status'}),price=el('strong',{class:'product-price',role:'status'});
 const inquire=btn('أضف إلى سلة الطلب',()=>{try{const fresh=products.find(x=>x.id===p.id),v=variants(fresh||{}).find(v=>v.id===variantSelect.value);D.assert(ready&&fresh?.published,'تعذر تحديث التوفر؛ أعد تحميل الصفحة.');addToCart(fresh,v,Number(q.value));}catch(e){notice(errorText(e),true);}},'button primary');
 function update(){selectedVariant=variantSelect.value;selectedQty=Number(q.value)||1;const v=vs.find(v=>v.id===selectedVariant);inquire.disabled=!ready||!v||v.price<=0;price.textContent=v?.price>0?formatShopMoney(v.price):'السعر قيد التحديث';msg.textContent=v?'الدفع بعد تأكيد الطلب. تُحدد رسوم الشحن عند المراجعة.':'غير متوفر حالياً.';}
 variantSelect.addEventListener('change',update);q.addEventListener('input',update);update();
 const related=visible().filter(x=>x.id!==p.id&&genusKey(x.genus)===genusKey(p.genus)).sort(byName).slice(0,8);
 $('product-view').replaceChildren(back,el('article',{class:'product-detail'},el('div',{},el('div',{class:'detail-image'},image(p)),el('p',{class:'hint'},p.image?(p.actualPhoto?'الصورة للقطعة الفعلية.':'الصورة تمثيلية؛ اطلب صورة القطعة قبل الشراء.'):'اطلب صور القطعة قبل تأكيد الطلب.',p.photoDate?' آخر تصوير: '+p.photoDate:'')),el('div',{class:'stack'},el('div',{class:'eyebrow'},genusSearch(p.genus)+' / '+p.code),el('h1',{class:'detail-name'},p.name),el('p',{},p.description||'راجع الصنف والصورة وأضف القطعة المناسبة إلى طلبك.'),p.size?el('p',{},'الحجم والحالة: '+p.size):null,p.care?el('p',{class:'muted'},'العناية: '+p.care):null,genusInfo(p.genus),el('label',{class:'field',for:'variant'},'الصنف / Plant form',variantSelect),el('label',{class:'field',for:'qty'},'الكمية المطلوبة',q),msg,el('div',{class:'detail-buybar'},price,inquire),btn('مراجعة سلة الطلب',openCart),el('p',{class:'hint'},'إرسال الطلب لا يحجز الكمية حتى يؤكده المتجر. تابع حالة طلبك من «حسابي / طلباتي».'))),...(related.length?[shelf('related','نباتات مشابهة',related,{limit:8})]:[]));}
setupDialog();initCheckout(()=>products);readURL();if('scrollRestoration'in history)history.scrollRestoration='manual';
$('demo-banner').hidden=!store.demo;$('home-link').href=home;$('shipping-policy').textContent=shopSettings.shipping;$('return-policy').textContent=shopSettings.returns;
$('search').addEventListener('input',()=>{activeGenus='';forceGrid=false;history.replaceState({},'',urlFor(null,''));render();});$('sort').addEventListener('change',render);
addEventListener('popstate',e=>{readURL();selectedVariant='';selectedQty=1;$('search').value=e.state?.shopView?.q||'';$('sort').value=e.state?.shopView?.sort||'name';render();restore(e.state?.shopView);});
try{await store.connect();store.subscribe('publicProducts',rows=>{const view={y:scrollY,tracks:Object.fromEntries([...document.querySelectorAll('.shelf-track')].map(t=>[t.id,t.scrollLeft]))};products=rows;ready=true;render();restore(view);},e=>{ready=false;render();notice('تعذر تحديث التوفر. أعد المحاولة قبل الطلب.',true);});}catch(e){ready=false;render();notice(errorText(e),true);}
