import * as store from './store.js';
import * as D from './domain.js';
import {shopSettings} from './config.js';
import {$,el,btn,notice,errorText} from './ui.js';
let products=[],activeId=new URLSearchParams(location.search).get('product'),selectedVariant='',selectedQty=1;
const home='shop.html'+(store.demo?'?demo=1':'');
const href=id=>home+(store.demo?'&':'?')+'product='+encodeURIComponent(id);
const variants=p=>(p.variants||[]).filter(v=>v.available>0);
const minimum=p=>{const prices=variants(p).map(v=>v.price).filter(n=>n>0);return prices.length?Math.min(...prices):Infinity;};
function placeholder(){return el('span',{class:'plant-placeholder'},el('img',{src:'brand-logo.jpeg',alt:'Temo_plants',width:'100',height:'100'}),el('small',{},'صورة النبات قريباً'));}
function image(p,cls=''){const src=D.safeImage(p.image);if(!src)return placeholder();const n=el('img',{src,alt:p.name,class:cls,loading:'lazy',decoding:'async',width:'800',height:'800'});n.addEventListener('error',()=>n.replaceWith(placeholder()));return n;}
function showProduct(id,push=true){activeId=id;selectedVariant='';selectedQty=1;if(push)history.pushState({},'',href(id));render();$('main').focus();scrollTo({top:0,behavior:'smooth'});}
function updateMeta(p){document.title=p?p.name+' | Temo Plants':'Temo Plants — نباتات نادرة';document.querySelector('meta[name="description"]').content=p?(p.description||p.name).slice(0,160):'كل ورقة تحكي شغف. نباتات نادرة وزراعة مائية من السعودية — Alocasia · Anthurium · Hoya.';let canonical=document.querySelector('link[rel=canonical]');if(shopSettings.canonicalBase){if(!canonical){canonical=el('link',{rel:'canonical'});document.head.append(canonical);}canonical.href=shopSettings.canonicalBase+'/shop.html'+(p?'?product='+encodeURIComponent(p.id):'');}}
function card(p){const price=minimum(p),a=el('a',{href:href(p.id),class:'product-visual','aria-label':'عرض '+p.name,onClick:e=>{e.preventDefault();showProduct(p.id);}},image(p),el('span',{class:'tag'},p.genus));return el('article',{class:'product-card'},a,el('div',{class:'product-content'},el('div',{class:'product-code'},p.code),el('h3',{},p.name),el('p',{class:'muted'},variants(p).map(v=>v.type).join(' · ')),el('div',{class:'price'},Number.isFinite(price)?(variants(p).length>1?'يبدأ من ':'')+D.formatMoney(price):'تواصل للسعر'),el('a',{href:href(p.id),class:'button',onClick:e=>{e.preventDefault();showProduct(p.id);}},'التفاصيل والطلب ↗')));}
function render(){if(activeId){detail();return;}$('hero').hidden=false;$('catalog-view').hidden=false;$('product-view').hidden=true;updateMeta(null);const q=$('search').value.trim().toLowerCase(),g=$('genus').value;let list=products.filter(p=>p.published&&variants(p).length&&(!g||p.genus===g)&&[p.name,p.code,p.genus].join(' ').toLowerCase().includes(q));const s=$('sort').value;if(s==='name')list.sort((a,b)=>a.name.localeCompare(b.name));else list.sort((a,b)=>s==='low'?minimum(a)-minimum(b):minimum(b)-minimum(a));$('count').textContent=list.length+' نبات';$('catalog').replaceChildren(...(list.length?list.map(card):[el('div',{class:'empty'},'لا توجد نباتات مطابقة الآن.',btn('عرض الكل',()=>{$('search').value='';$('genus').value='';render();}))]));}
function detail(){const p=products.find(p=>p.id===activeId&&p.published);$('hero').hidden=true;$('catalog-view').hidden=true;$('product-view').hidden=false;const back=el('a',{href:home,class:'button subtle',onClick:e=>{e.preventDefault();activeId=null;history.pushState({},'',home);render();}},'→ العودة للمجموعة');if(!p){$('product-view').replaceChildren(back,el('div',{class:'empty'},'هذا النبات غير معروض حالياً.'));updateMeta(null);return;}
  updateMeta(p);const vs=variants(p);if(!vs.some(v=>v.id===selectedVariant))selectedVariant=vs[0]?.id||'';const variantSelect=el('select',{id:'variant','aria-label':'اختيار الصنف'},vs.map(v=>el('option',{value:v.id,...(v.id===selectedVariant?{selected:''}:{})},v.type+' · '+(v.price?D.formatMoney(v.price):'تواصل للسعر'))));const q=el('input',{id:'qty',type:'number',min:'1',step:'1',value:String(selectedQty),'aria-label':'الكمية'});const msg=el('p',{class:'hint',role:'status'}),copy=btn('نسخ تفاصيل الطلب',async()=>{const fresh=products.find(x=>x.id===p.id),v=fresh?.variants.find(v=>v.id===variantSelect.value);try{const qty=D.quantity(q.value);D.assert(fresh?.published&&v&&v.available>=qty,'تغير التوفر. اختر كمية متاحة.');const text=`مرحباً Temo Plants 🌿\nأرغب بالاستفسار عن:\n${fresh.name}\nالكود: ${fresh.code}\nالصنف: ${v.type}\nالكمية: ${qty}\n${v.price?'قيمة النباتات: '+D.formatMoney(v.price*qty):'أرجو تأكيد السعر'}\nالرابط: ${location.href}\nأرجو تأكيد التوفر والشحن.`;try{await navigator.clipboard.writeText(text);notice('نُسخت التفاصيل. افتح Instagram وألصقها في المحادثة.');}catch{const box=el('textarea',{'aria-label':'تفاصيل الطلب للنسخ',readonly:''});box.value=text;msg.replaceChildren('انسخ النص التالي ثم افتح Instagram:',box);box.select();}}catch(e){notice(errorText(e),true);}},'button primary');const link=el('a',{href:'https://ig.me/m/'+encodeURIComponent(shopSettings.instagram),target:'_blank',rel:'noopener noreferrer',class:'button'},'فتح محادثة Instagram ↗');
  function update(){selectedVariant=variantSelect.value;selectedQty=Number(q.value)||1;const v=vs.find(x=>x.id===selectedVariant);q.max=String(v?.available||0);copy.disabled=!v;msg.textContent=v?`متاح للاستفسار: ${v.available} · الشحن يؤكد قبل الدفع.`:'نفد المخزون حالياً. يمكنك الاستفسار عن موعد التوفر.';}variantSelect.addEventListener('change',update);q.addEventListener('input',()=>selectedQty=Number(q.value));update();
  $('product-view').replaceChildren(back,el('article',{class:'product-detail'},el('div',{},el('div',{class:'detail-image'},image(p)),el('p',{class:'hint'},p.image?(p.actualPhoto?'الصورة للقطعة الفعلية.':'الصورة تمثيلية؛ اطلب صورة القطعة قبل الشراء.'):'اطلب صور القطعة قبل تأكيد الطلب.',p.photoDate?' آخر تصوير: '+p.photoDate:'')),el('div',{class:'stack'},el('div',{class:'eyebrow'},p.genus+' / '+p.code),el('h1',{class:'detail-name'},p.name),el('p',{},p.description||'راسلنا لمعرفة تفاصيل هذه النبتة وحالتها.'),p.size?el('p',{},'الحجم والحالة: '+p.size):null,p.care?el('p',{class:'muted'},'العناية: '+p.care):null,el('label',{class:'field',for:'variant'},'الصنف',variantSelect),el('label',{class:'field',for:'qty'},'الكمية',q),msg,copy,link,el('p',{class:'hint'},'1. انسخ تفاصيل الطلب. 2. افتح Instagram وألصقها. الاستفسار لا يحجز الكمية.'))));
}
$('demo-banner').hidden=!store.demo;$('home-link').href=home;$('shipping-policy').textContent=shopSettings.shipping;$('return-policy').textContent=shopSettings.returns;
for(const n of ['search','genus','sort'])$(n).addEventListener(n==='search'?'input':'change',render);
addEventListener('popstate',()=>{activeId=new URLSearchParams(location.search).get('product');render();});
try{await store.connect();store.subscribe('publicProducts',rows=>{products=rows;const g=$('genus').value;const genera=[...new Set(products.filter(p=>p.published).map(p=>p.genus))];$('genus').replaceChildren(el('option',{value:''},'كل الأنواع'),...genera.map(g=>el('option',{value:g},g)));$('genus').value=genera.includes(g)?g:'';render();},e=>{$('catalog').replaceChildren(el('div',{class:'empty'},errorText(e),btn('إعادة المحاولة',()=>location.reload())));notice('تعذر تحديث التوفر. أعد المحاولة قبل الطلب.',true);});}catch(e){$('catalog').replaceChildren(el('div',{class:'empty'},errorText(e),el('a',{class:'button',href:'shop.html?demo=1'},'استعراض النسخة التجريبية')));}
