import {formatMoney} from './domain.js';
export const $=id=>document.getElementById(id);
export function el(tag,attrs={},...children){const n=document.createElement(tag);for(const [k,v]of Object.entries(attrs)){if(v===null||v===undefined)continue;if(k==='class')n.className=v;else if(k.startsWith('on'))n.addEventListener(k.slice(2).toLowerCase(),v);else if(k==='text')n.textContent=v;else if(k==='value')n.value=v;else if(k==='checked')n.checked=!!v;else if(k==='disabled')n.disabled=!!v;else n.setAttribute(k,String(v));}children.flat(Infinity).filter(x=>x!==null&&x!==undefined).forEach(c=>n.append(c instanceof Node?c:document.createTextNode(String(c))));return n;}
export function btn(text,fn,cls='button'){return el('button',{type:'button',class:cls,onClick:async event=>{try{await fn(event);}catch(e){notice(errorText(e),true);}}},text);}
export function field(label,name,type='text',value='',attrs={}){const i=el(type==='textarea'?'textarea':'input',{id:'f-'+name,name,type:type==='textarea'?null:type,value,...attrs});if(type==='textarea')i.value=value;return el('label',{class:'field',for:'f-'+name},el('span',{},label),i);}
export function select(label,name,options,value=''){return el('label',{class:'field',for:'f-'+name},el('span',{},label),el('select',{id:'f-'+name,name,'aria-label':label},options.map(([v,t])=>el('option',{value:v,...(v===value?{selected:''}:{})},t))));}
export function check(label,name,value=false){return el('label',{class:'check'},el('input',{name,type:'checkbox',checked:value}),label);}
export function notice(message,bad=false){const n=$('notice');n.textContent=message;n.className='notice'+(bad?' error':'');n.hidden=false;clearTimeout(notice.timer);notice.timer=setTimeout(()=>n.hidden=true,bad?15000:6000);}
export function errorText(e){if(e?.code==='permission-denied')return 'الصلاحيات غير مفعلة لهذا الحساب. راجع قواعد Firebase وإضافة UID.';if(e?.code?.startsWith('auth/'))return 'تعذر تسجيل الدخول. تحقق من الحساب وكلمة المرور وتفعيل Email/Password.';if(e?.code==='unavailable')return 'الاتصال غير متاح. احتفظ بالنموذج وحاول مجدداً.';return e?.message||'تعذر إكمال العملية.';}
let opener=null;
export function dialog(title,content,onSubmit){const d=$('dialog');if(d.open)d.close();opener=document.activeElement;d.replaceChildren();const form=el('form',{class:'dialog-form'}),err=el('p',{class:'form-error',role:'alert'});form.append(el('div',{class:'dialog-head'},el('h2',{id:'dialog-title'},title),btn('إغلاق',()=>{if(d.dataset.busy!=='1')d.close();},'button subtle')),content,err);if(onSubmit){const submit=el('button',{type:'submit',class:'button primary'},'حفظ وتأكيد');form.append(el('div',{class:'dialog-actions'},submit,btn('إلغاء',()=>{if(d.dataset.busy!=='1')d.close();},'button subtle')));form.addEventListener('submit',async e=>{e.preventDefault();if(submit.disabled)return;err.textContent='';submit.disabled=true;submit.textContent='جارٍ الحفظ…';d.dataset.busy='1';try{const result=await onSubmit(new FormData(form),form);d.dataset.busy='';d.close();notice(typeof result==='string'&&result.length>40?result:'تم الحفظ بنجاح.');}catch(ex){err.textContent=errorText(ex);}finally{submit.disabled=false;submit.textContent='حفظ وتأكيد';d.dataset.busy='';}});}d.append(form);d.setAttribute('aria-labelledby','dialog-title');d.showModal();}
export function setupDialog(){const d=$('dialog');d.addEventListener('cancel',e=>{if(d.dataset.busy==='1')e.preventDefault();});d.addEventListener('close',()=>opener?.focus());}
export function table(headers,rows){return el('div',{class:'table-wrap',tabindex:'0','aria-label':'جدول قابل للتمرير'},el('table',{},el('thead',{},el('tr',{},headers.map(h=>el('th',{scope:'col'},h)))),el('tbody',{},rows.length?rows.map(row=>el('tr',{},row.map(c=>el('td',{},c)))):el('tr',{},el('td',{colspan:headers.length,class:'empty'},'لا توجد سجلات بعد.')))));}
export const moneyNode=n=>el('span',{class:'money'},formatMoney(n));
export function download(name,data){const blob=new Blob([JSON.stringify(data,null,2)],{type:'application/json;charset=utf-8'}),url=URL.createObjectURL(blob),a=el('a',{href:url,download:name});a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}

